### PR TITLE
Feng Office: Update to v3.11.2.8

### LINKED ISSUE #2348: Feng Office Installer Claims MySQL Root Password is Incorrect
### Setup

_Package Name:_  Feng Office
_Package Version:_ 2.5.1.2-3

_NAS Model:_ DS414
_NAS Architecture:_
_DSM version:_ DSM 6.0-7321 Update 6
### Expected behavior

The installation process to accept the MySQL correct root password and complete installing the package
### Actual behavior

The installation process aborts claiming the MySQL root password is incorrect 
### Steps to reproduce

_1._ Open Package Center
_2._ Click Community Tab
_3._ Select Feng Office
_4._ Click Install
_5._ Enter MySQL root password
_6._ Enter Feng Office MySQL user password
_7._ Click Next
_8._ Enter Domain name
_9._ Click Next
_10._ Confirm settings and click Apply
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
No log file
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
2016/05/27 10:55:41 install  :
            End:    /bin/mkdir -p /volume1/@tmp/pkginstall/package  ret=[0]
2016/05/27 10:55:41 install  :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/fengoffice/@SYNOPKG_DOWNLOAD_fengoffice -C /volume1/@tmp/pkginstall --no-same-owner
2016/05/27 10:55:41 install  :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/fengoffice/@SYNOPKG_DOWNLOAD_fengoffice -C /volume1/@tmp/pkginstall --no-same-owner    ret=[0]
2016/05/27 10:55:41 install fengoffice 2.5.1.2-3:
            Begin:  /bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            End:    /bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner    ret=[0]
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            Begin:  preinst
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            End:    preinst ret=[1]
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            Begin:  /bin/rm -rf /volume1/@tmp/pkginstall
2016/05/27 10:55:44 install fengoffice 2.5.1.2-3:
            End:    /bin/rm -rf /volume1/@tmp/pkginstall    ret=[0]
2016/05/27 10:55:44 install fengoffice 2.5.1.2-3 failed

```

### LINKED ISSUE #4230: Apollolake package for Feng Office requested
I can see Feng Office packages available for other architectures, but not for Apollolake.  Can this be made available for Apollolake to run on the DS918+?

Thanks in advance

_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Feng Office 
_Package Version:_ v2.5.1.2-3

_NAS Model:_ DS918+
_NAS Architecture:_ Apollolake
_DSM version:_ 6.2.3

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR contains the following:

1. Upgrade Feng Office to version 3.11.2.8
2. Modernise package scripts
3. Add PHP profiles for DSM 6
4. Add full backup and restore

Fixes #2348
Closes #4230

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
hey @hgy59, I was attempting to upgrade this package but ran into some problems with the installer. With the earlier package it seems the original contributor sent some arguments to a supplemental installer which automated the first three steps of the four step wizard.

Running this with it's original setup I got the following in the installer log:

```
2024/01/26 21:57:21	===> Step postinst. STATUS=INSTALL USER=fengoffice GROUP= SHARE_PATH=
2024/01/26 21:57:21	Begin save_wizard_variables
2024/01/26 21:57:21	End save_wizard_variables
2024/01/26 21:57:21	Begin syno_sync_var_folder
2024/01/26 21:57:21	End syno_sync_var_folder
2024/01/26 21:57:21	Begin service_postinst
2024/01/26 21:57:21	PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /volume1/web_packages/fengoffice/public/install/installation/acInstallation.class.php:113
2024/01/26 21:57:21	Stack trace:
2024/01/26 21:57:21	#0 /volume1/web_packages/fengoffice/public/install/installation/steps/FinishStep.class.php(56): acInstallation->execute()
2024/01/26 21:57:21	#1 /volume1/web_packages/fengoffice/public/install/library/classes/ScriptInstaller.class.php(93): FinishStep->execute()
2024/01/26 21:57:21	#2 /volume1/web_packages/fengoffice/public/install/install_helper.php(8): ScriptInstaller->executeStep(4)
2024/01/26 21:57:21	#3 {main}
2024/01/26 21:57:21	  thrown in /volume1/web_packages/fengoffice/public/install/installation/acInstallation.class.php on line 113
2024/01/26 21:57:21	End service_postinst
```

My assessment of this was that the PHP execution did not include the extensions that would normally be included with the FPM service and these needed to be manually included.

In this state however the wizard was able to be manually run and if you configure all the required fields the installation would complete and the platform seem to function (under DSM 7; haven't completed the DSM 6 stuff yet).

I then modified the script to include the PHP extensions. While there were no longer errors in the install log, the service log spat out an HTML page (https://pastebin.com/RNrxGT3u), which contained the error:

```
Found faulty query: INSERT INTO `fo_members` (`dimension_id`,`object_type_id`, `parent_member_id`, `depth`, `name`, `object_id` ) SELECT (SELECT `id` FROM `fo_dimensions` WHERE `code`='feng_persons'), (SELECT `id` FROM `fo_object_types` WHERE `name`='company'), 0, 1, `o`.`name`, `o`.`id` FROM `fo_objects` `o` INNER JOIN `fo_contacts` `c` ON `c`.`object_id`=`o`.`id` WHERE `c`.`is_company`=1 ON DUPLICATE KEY UPDATE dimension_id=dimension_id
Error while loading inital data for plugin 'core_dimensions'. Field 'description' doesn't have a default value
```

Now I don't know if this is a warning or an error preventing setup but the webpage does not load after the installation is completed. This is unlike when the automatic setup was not working before. I am not sure what else can be done to resolve this other than requiring the user to just do all the wizard steps. The challenge with that is that the wizard often times out when the database is being setup and only after trying to load the webpage a few times does the interface come up.

Don't know if you have any ideas.

**Comment by mreid-tt** [comment]
@hgy59, I believe this package update is now complete. Let me know if you have any thoughts from your review.

File: spk/fengoffice/src/conf_6/privilege [hunk 1]
```diff
@@ -0,0 +1,53 @@
+{
+    "defaults": {
+        "run-as": "package"
+    },
```
Comment (hgy59) [inline spk/fengoffice/src/conf_6/privilege:4]: Why not define default "run-as": "root" instead of "package"?
Than you do not need to overwrite all actions with "run-as": "root".

**Comment by hgy59** [comment]
@mreid-tt I will need additional cycles for a deeper review.

But one question already popped up:
We have a default uninstall wizard for all DSM 7 packages, that asks whether to remove all package data.
There are some additional folders that must be removed/cleaned by the uninstaller, when `(*) Erase all of the package data files. (Not Recverable),` is selected. Otherwise on DSM 7 even the fengoffice database must be kept.

File: spk/fengoffice/src/conf_6/privilege (hunk 1 above)
Comment (mreid-tt) [reply spk/fengoffice/src/conf_6/privilege]: Makes sense. Done.

**Comment by mreid-tt** [comment]
> We have a default uninstall wizard for all DSM 7 packages, that asks whether to remove all package data.
> There are some additional folders that must be removed/cleaned by the uninstaller, when `(*) Erase all of the package data files. (Not Recverable),` is selected. Otherwise on DSM 7 even the fengoffice database must be kept.

When I was working on ownCloud I opted for the complete removal of the package along with a robust backup mechanism to include the database and the data. Because the data is in the web folder I suspect I'll need to expand the backup function for FengOffice as well to include same.

If I leave the database but the web data gets removed then it doesn't really benefit the user in my opinion. So with a good backup, the default action would be to erase all package data files.

**Comment by hgy59** [comment]
> If I leave the database but the web data gets removed then it doesn't really benefit the user in my opinion. So with a good backup, the default action would be to erase all package data files.

✅ Ok, I got it. You have a hidden field in the uninstall wizard file that ensures that `wizard_delete_data=true`, and the folders I missed are cleanup up...
```json
 	{
		"type": "multiselect",
		"subitems": [{
			"key": "wizard_delete_data",
			"hidden": true,
			"defaultValue": true
		}]
	}
```

**Comment by mreid-tt** [comment]
I've completed testing of the new backup and restore as well as simulated an upgrade from v3.11.1.2 to v3.11.1.19. Overall things work well in DSM 7 but there was one exception for the upgrade process for DSM 6.

In DSM 7, the service log for an upgrade on a backup restore shows the following:
```
Config file found and loaded.
File '/config/config.php' exists and is writable
Folder '/config' exists and is writable
Folder '/cache' exists and is writable
Folder '/tmp' exists and is writable
Folder '/upload' exists and is writable
Extension 'mysqli' is loaded
Extension 'gd' is loaded
Extension 'simplexml' is loaded
Upgrade script has connected to the database.
Test query has been executed. Its safe to proceed with database migration.
2024-09-11 20:30:20 - Starting upgrade to 3.11.1.19
Database schema transformations executed (total queries: 10)
Feng Office has been upgraded. You are now running Feng Office 3.11.1.19 Enjoy!
2024-09-11 20:30:22 - Finished upgrade to 3.11.1.19
Updating plugins...
Finished plugins update.
Plugin mail updated successfully
Installation log: /var/log/packages/fengoffice.log
Starting fengoffice ...
Wed Sep 11 16:30:44 -04 2024
```

However in DSM 6 for an upgrade on a backup restore we see the following:
```
Config file found and loaded.
File '/config/config.php' exists and is writable
Folder '/config' exists and is writable
Folder '/cache' exists and is writable
Folder '/tmp' exists and is writable
Folder '/upload' exists and is writable
Extension 'mysqli' is loaded
Extension 'gd' is loaded
Extension 'simplexml' is loaded
Upgrade script has connected to the database.
Test query has been executed. Its safe to proceed with database migration.
2024-09-11 23:08:09 - Starting upgrade to 3.11.1.19
Database schema transformations executed (total queries: 10)
Feng Office has been upgraded. You are now running Feng Office 3.11.1.19 Enjoy!
2024-09-11 23:08:09 - Finished upgrade to 3.11.1.19
Error: Error found when updating plugins
Error: To finish updating the plugins please try executing the following command in your terminal:
Error: php /volume1/web/fengoffice/public/install/plugin-console.php update_all
Plugin mail updated successfully
Installation log: /var/log/packages/fengoffice.log
Starting fengoffice ...
Wed Sep 11 19:08:28 -04 2024
```

When attempting a normal package upgrade we see a similar error with a bit more detail for DSM 6:
```
Config file found and loaded.
File '/config/config.php' exists and is writable
Folder '/config' exists and is writable
Folder '/cache' exists and is writable
Folder '/tmp' exists and is writable
Folder '/upload' exists and is writable
Extension 'mysqli' is loaded
Extension 'gd' is loaded
Extension 'simplexml' is loaded
Upgrade script has connected to the database.
Test query has been executed. Its safe to proceed with database migration.
2024-09-12 00:27:58 - Starting upgrade to 3.11.1.19
Database schema transformations executed (total queries: 72)
Feng Office has been upgraded. You are now running Feng Office 3.11.1.19 Enjoy!
2024-09-12 00:28:28 - Finished upgrade to 3.11.1.19
PHP Fatal error:  Call to undefined function mysqli_connect() in /volume1/web/fengoffice/application/functions.php on line 34
PHP Fatal error:  Class 'DB' not found in /volume1/web/fengoffice/application/functions.php on line 69
Error: Error found when updating plugins
Error: To finish updating the plugins please try executing the following command in your terminal:
Error: php /volume1/web/fengoffice/public/install/plugin-console.php update_all
Plugin mail updated successfully
```

All the PHP extensions are properly enabled as far as I can tell and all other functions seem to work well. Unsure as to the specific reason this is an issue under DSM 6.

**Comment by mreid-tt** [comment]
@hgy59, I believe the update is now complete. During the process, I realized that the path validation functions, or any functions that used `exit 1`, only worked within those starting with `validate_`. Therefore, I restructured the uninstall functions to separate validation from execution. These changes have also been applied to ownCloud in #6225. I’d appreciate any feedback you may have on your review.

**Comment by mreid-tt** [comment]
> All the PHP extensions are properly enabled as far as I can tell and all other functions seem to work well. Unsure as to the specific reason this is an issue under DSM 6.

Okay, I've investigated this further and manually performed an upgrade based on the documentation on [Upgrading Feng Office](https://wiki.fengoffice.com/doku.php/installation:migration). My results were as follows:

```
$ cd /var/services/web
$ sudo rsync -aX -I fengoffice-new/share/fengoffice/ fengoffice
$ PHP_SETTINGS=$(jq -r '.extensions | map("-d extension=" + . + ".so") | join(" ")' /var/packages/fengoffice/target/web/fengoffice.json)
$ PHP_SETTINGS="${PHP_SETTINGS} -d mysqli.default_socket=/run/mysqld/mysqld10.sock"
```
```
$ sudo -u http /usr/local/bin/php74 $PHP_SETTINGS /var/services/web/fengoffice/public/upgrade/console.php

Config file found and loaded.
File '/config/config.php' exists and is writable
Folder '/config' exists and is writable
Folder '/cache' exists and is writable
Folder '/tmp' exists and is writable
Folder '/upload' exists and is writable
Extension 'mysqli' is loaded
Extension 'gd' is loaded
Extension 'simplexml' is loaded
Upgrade script has connected to the database.
Test query has been executed. Its safe to proceed with database migration.
2024-09-15 01:49:56 - Starting upgrade to 3.11.1.19
Database schema transformations executed (total queries: 10)
Feng Office has been upgraded. You are now running Feng Office 3.11.1.19 Enjoy!
2024-09-15 01:49:59 - Finished upgrade to 3.11.1.19
Error: Error found when updating plugins
Error: To finish updating the plugins please try executing the following command in your terminal:
Error: php /volume1/web/fengoffice/public/install/plugin-console.php update_all

$ sudo -u http /usr/local/bin/php74 $PHP_SETTINGS /var/services/web/fengoffice/public/install/plugin-console.php update_all

Plugin mail updated successfully
```
```
$ sudo -u http /usr/local/bin/php74 $PHP_SETTINGS /var/services/web/fengoffice/public/upgrade/console.php

There is no upgrade path from version 3.11.1.19 to 3.11.1.19.

$ sudo -u http /usr/local/bin/php74 $PHP_SETTINGS /var/services/web/fengoffice/public/install/plugin-console.php update_all

$ <<end>>
```

Although an initial error occurs when updating the plugins during the upgrade process, they are successfully updated afterward using a specific command. This aligns with the documentation, which states:

> While sometimes this does work automatically, it is recommended that you always run and [update the plugins](https://wiki.fengoffice.com/doku.php/installation:migration#plugins_installation_and_updates) as well

Therefore, the error reported in the DSM 6 service log during the upgrade is promptly resolved by the plugin update command within the script.

File: spk/fengoffice/src/wizard/install_uifile.sh [hunk 2]
```diff
@@ -200,7 +200,7 @@ PAGE_INSTALL_CONFIG=$(/bin/cat<<EOF
         "desc": "A 'fengoffice' MySQL user and database will be created. Please provide a password for the 'fengoffice' user.",
         "subitems": [{
             "key": "wizard_mysql_password_fengoffice",
-            "desc": "fengoffice password",
+            "desc": "User password",
```
Comment (hgy59) [inline spk/fengoffice/src/wizard/install_uifile.sh:203]: now it does not match the description above, that says it is the password for the `'fengoffice' user`

To make it clear I propose to adjust both subitem descriptions:

`MySQL 'root' password` - instead of `Root password`
and
`MySQL 'fengoffice' password` - instead of `fengoffice password` or `User password`

Comment (mreid-tt) [reply spk/fengoffice/src/wizard/install_uifile.sh]: I've updated the descriptions accordingly. If we are to standardise this, many other package wizards will need to be updated in the future.
