### PR TITLE
Sonarr: fixes for services and package modernisation

### LINKED ISSUE #5450: Sonarr uninstall not removing 'appdata' when erasing all data files
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Sonarr

### Package Version

20210717-19

### Device Model

DS916+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 1

### What happened?

When uninstalling Sonarr and selecting `Erase all of the package data files. (Not Recoverable)` the files in the AppData directory do not get removed. This results in an error on re-install of the package: `The DataMapper was unable to load the following field: 'Languages'`. This is as a result of mismatched configuration versions.

### Reproduction steps

```bash
1. Install Sonarr 20210717-19
2. Run internal updater to update to current version
3. Uninstall Sonarr
4. Reinstall Sonarr 20210717-19
5. Open Sonarr webpage
```

### Install Log

```log
`/var/log/packages/nzbdrone.log`

2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin preinst
2022/10/14 20:59:43	===> Step preinst. USER=sc-nzbdrone GROUP=sc-download SHARE_PATH=
2022/10/14 20:59:43	install nzbdrone 20210717-19 End preinst ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/mkdir -p /volume1/@appstore/nzbdrone -m 755
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/mkdir -p /volume1/@appstore/nzbdrone -m 755 ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/rm -rf /volume1/@appstore/nzbdrone
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/rm -rf /volume1/@appstore/nzbdrone ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/package /volume1/@appstore/nzbdrone
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/package /volume1/@appstore/nzbdrone ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/mkdir -p /var/packages/nzbdrone -m 755
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/mkdir -p /var/packages/nzbdrone -m 755 ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/touch /var/packages/nzbdrone/installing
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/touch /var/packages/nzbdrone/installing ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/INFO /var/packages/nzbdrone/INFO
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/INFO /var/packages/nzbdrone/INFO ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone/scripts
2022/10/14 20:59:43	install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone/scripts ret=[0]
2022/10/14 20:59:43	install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/scripts /var/packages/nzbdrone/scripts
2022/10/14 20:59:44	install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/scripts /var/packages/nzbdrone/scripts ret=[0]
2022/10/14 20:59:44	install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone/WIZARD_UIFILES
2022/10/14 20:59:44	install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone/WIZARD_UIFILES ret=[0]
2022/10/14 20:59:44	install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/WIZARD_UIFILES /var/packages/nzbdrone/WIZARD_UIFILES
2022/10/14 20:59:44	install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/WIZARD_UIFILES /var/packages/nzbdrone/WIZARD_UIFILES ret=[0]
2022/10/14 20:59:44	install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone/conf
2022/10/14 20:59:44	install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone/conf ret=[0]
2022/10/14 20:59:44	install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/conf /var/packages/nzbdrone/conf
2022/10/14 20:59:44	install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/conf /var/packages/nzbdrone/conf ret=[0]
2022/10/14 20:59:49	install nzbdrone 20210717-19 Begin postinst
2022/10/14 20:59:49	===> Step postinst. USER=sc-nzbdrone GROUP=sc-download SHARE_PATH=
2022/10/14 20:59:49	Begin service_postinst
2022/10/14 20:59:49	Notice: set_unix_permissions() is no longer required on DSM7.
2022/10/14 20:59:49	End service_postinst
2022/10/14 20:59:49	install nzbdrone 20210717-19 End postinst ret=[0]
2022/10/14 20:59:50	install nzbdrone 20210717-19 Begin start-stop-status start
2022/10/14 20:59:55	install nzbdrone 20210717-19 End start-stop-status start ret=[0]
2022/10/14 21:10:42	uninstall nzbdrone 20210717-19 Begin start-stop-status stop
2022/10/14 21:10:43	uninstall nzbdrone 20210717-19 End start-stop-status stop ret=[0]
2022/10/14 21:10:44	uninstall nzbdrone 20210717-19 Begin preuninst
2022/10/14 21:10:44	===> Step preuninst. USER=sc-nzbdrone GROUP=sc-download SHARE_PATH=
2022/10/14 21:10:44	uninstall nzbdrone 20210717-19 End preuninst ret=[0]
2022/10/14 21:10:45	uninstall nzbdrone 20210717-19 Begin /bin/rm -rf /volume1/@appstore/nzbdrone
2022/10/14 21:10:45	uninstall nzbdrone 20210717-19 End /bin/rm -rf /volume1/@appstore/nzbdrone ret=[0]
2022/10/14 21:10:45	uninstall nzbdrone 20210717-19 Begin /bin/rm -rf /volume1/@apptemp/nzbdrone
2022/10/14 21:10:45	uninstall nzbdrone 20210717-19 End /bin/rm -rf /volume1/@apptemp/nzbdrone ret=[0]
2022/10/14 21:10:45	uninstall nzbdrone 20210717-19 Begin postuninst
2022/10/14 21:10:45	===> Step postuninst. USER=sc-nzbdrone GROUP=sc-download SHARE_PATH=
2022/10/14 21:10:45	uninstall nzbdrone 20210717-19 End postuninst ret=[0]
```

### Service Log

```log
`/var/packages/nzbdrone/var/nzbdrone.log`

Fri Oct 14 21:24:19 -04 2022
Starting nzbdrone command env PATH=/var/packages/mono/target/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appdata/nzbdrone LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib /var/packages/mono/target/bin/mono /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe 
[Info] Bootstrap: Starting Sonarr - /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe - Version 3.0.5.1144 
[Info] Router: Application mode: Interactive 
[Info] MigrationLogger: *** Migrating data source=/volume1/@appdata/nzbdrone/.config/Sonarr/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLogger: *** Migrating data source=/volume1/@appdata/nzbdrone/.config/Sonarr/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://*:8989/ 
[Info] SonarrBootstrapper: Starting Web Server 
[Error] EventAggregator: LanguageProfileService failed while processing [ApplicationStartedEvent] 

[v3.0.5.1144] Marr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Languages' value: '[
  {
    "language": 30,
    "allowed": false
  },
  {
    "language": 29,
    "allowed": false
  },
  {
    "language": 28,
    "allowed": false
  },
  {
    "language": 13,
    "allowed": false
  },
  {
    "language": 0,
    "allowed": false
  },
  {
    "language": 17,
    "allowed": false
  },
  {
    "language": 14,
    "allowed": false
  },
  {
    "language": 3,
    "allowed": false
  },
  {
    "language": 11,
    "allowed": false
  },
  {
    "language": 18,
    "allowed": false
  },
  {
    "language": 12,
    "allowed": false
  },
  {
    "language": 15,
    "allowed": false
  },
  {
    "language": 24,
    "allowed": false
  },
  {
    "language": 21,
    "allowed": false
  },
  {
    "language": 8,
    "allowed": false
  },
  {
    "language": 5,
    "allowed": false
  },
  {
    "language": 9,
    "allowed": false
  },
  {
    "language": 22,
    "allowed": false
  },
  {
    "language": 27,
    "allowed": false
  },
  {
    "language": 23,
    "allowed": false
  },
  {
    "language": 20,
    "allowed": false
  },
  {
    "language": 4,
    "allowed": false
  },
  {
    "language": 2,
    "allowed": false
  },
  {
    "language": 19,
    "allowed": false
  },
  {
    "language": 16,
    "allowed": false
  },
  {
    "language": 1,
    "allowed": true
  },
  {
    "language": 7,
    "allowed": false
  },
  {
    "language": 6,
    "allowed": false
  },
  {
    "language": 25,
    "allowed": false
  },
  {
    "language": 10,
    "allowed": false
  },
  {
    "language": 26,
    "allowed": false
  }
]'. ID does not match a known language
Parameter name: id ---> System.ArgumentException: ID does not match a known language
Parameter name: id
  at NzbDrone.Core.Languages.Language.FindById (System.Int32 id) [0x00018] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Languages.Language.op_Explicit (System.Int32 id) [0x00000] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Datastore.Converters.LanguageIntConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x0000d] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) [0x00056] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00280] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00161] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) [0x00173] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) [0x000dc] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0007f] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at NzbDrone.Core.Datastore.Converters.EmbeddedDocumentConverter.FromDB (Marr.Data.Converters.ConverterContext context) [0x00035] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x00067] in <8e71e0241103454486ee48e8b5b558db>:0 
   --- End of inner exception stack trace ---
  at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x000b3] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity (System.Type entityType, Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00012] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity[T] (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00000] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection`1[T] entityList, System.Boolean useAltName) [0x0008d] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00052] in <8e71e0241103454486ee48e8b5b558db>:0 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].All () [0x0000b] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Profiles.Languages.LanguageProfileService.All () [0x00000] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Profiles.Languages.LanguageProfileService.Handle (NzbDrone.Core.Lifecycle.ApplicationStartedEvent message) [0x00000] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (TEvent event) [0x0011a] in <eea51fec6dbe458b873ba10bf3c0a405>:0 

[Fatal] SonarrErrorPipeline: Request Failed. GET /api/v3/languageprofile 

[v3.0.5.1144] Marr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Languages' value: '[
  {
    "language": 30,
    "allowed": false
  },
  {
    "language": 29,
    "allowed": false
  },
  {
    "language": 28,
    "allowed": false
  },
  {
    "language": 13,
    "allowed": false
  },
  {
    "language": 0,
    "allowed": false
  },
  {
    "language": 17,
    "allowed": false
  },
  {
    "language": 14,
    "allowed": false
  },
  {
    "language": 3,
    "allowed": false
  },
  {
    "language": 11,
    "allowed": false
  },
  {
    "language": 18,
    "allowed": false
  },
  {
    "language": 12,
    "allowed": false
  },
  {
    "language": 15,
    "allowed": false
  },
  {
    "language": 24,
    "allowed": false
  },
  {
    "language": 21,
    "allowed": false
  },
  {
    "language": 8,
    "allowed": false
  },
  {
    "language": 5,
    "allowed": false
  },
  {
    "language": 9,
    "allowed": false
  },
  {
    "language": 22,
    "allowed": false
  },
  {
    "language": 27,
    "allowed": false
  },
  {
    "language": 23,
    "allowed": false
  },
  {
    "language": 20,
    "allowed": false
  },
  {
    "language": 4,
    "allowed": false
  },
  {
    "language": 2,
    "allowed": false
  },
  {
    "language": 19,
    "allowed": false
  },
  {
    "language": 16,
    "allowed": false
  },
  {
    "language": 1,
    "allowed": true
  },
  {
    "language": 7,
    "allowed": false
  },
  {
    "language": 6,
    "allowed": false
  },
  {
    "language": 25,
    "allowed": false
  },
  {
    "language": 10,
    "allowed": false
  },
  {
    "language": 26,
    "allowed": false
  }
]'. ID does not match a known language
Parameter name: id ---> System.ArgumentException: ID does not match a known language
Parameter name: id
  at NzbDrone.Core.Languages.Language.FindById (System.Int32 id) [0x00018] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Languages.Language.op_Explicit (System.Int32 id) [0x00000] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Datastore.Converters.LanguageIntConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x0000d] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) [0x00056] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00280] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00161] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) [0x00173] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) [0x000dc] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0007f] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at NzbDrone.Core.Datastore.Converters.EmbeddedDocumentConverter.FromDB (Marr.Data.Converters.ConverterContext context) [0x00035] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x00067] in <8e71e0241103454486ee48e8b5b558db>:0 
   --- End of inner exception stack trace ---
  at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x000b3] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity (System.Type entityType, Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00012] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity[T] (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00000] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection`1[T] entityList, System.Boolean useAltName) [0x0008d] in <8e71e0241103454486ee48e8b5b558db>:0 
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00052] in <8e71e0241103454486ee48e8b5b558db>:0 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].All () [0x0000b] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at NzbDrone.Core.Profiles.Languages.LanguageProfileService.All () [0x00000] in <eea51fec6dbe458b873ba10bf3c0a405>:0 
  at Sonarr.Api.V3.Profiles.Language.LanguageProfileModule.GetAll () [0x00000] in <5c69f5b136214a078340b2085574c96c>:0 
  at Sonarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00006] in <ae7b8dd7b8b84e52a539117d478818e1>:0 
  at Nancy.NancyModule+<>c__DisplayClass14_0`1[T].<Get>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyModule+<>c__DisplayClass16_0`1[T].<Get>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0 
  at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 

[Warn] MonoDebugCheck: Mono is not running with --debug switch 
[Info] RssSyncService: Starting RSS Sync 
[Warn] FetchAndParseRssService: No available indexers. check your configuration. 
[Info] DownloadDecisionMaker: No results found 
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0
```

### Other Logs

```log
`/var/log/synopkg.log`

2022/10/14 20:59:20 download nzbdrone https://packages.synocommunity.com/nzbdrone/19/nzbdrone.v19.f40000%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=kvmx64&build=42962 End download
2022/10/14 20:59:21 Use given volume to install, volume=[]
2022/10/14 20:59:21 Use any available volume to install, volume=[/volume1]
2022/10/14 20:59:41 Use given volume to install, volume=[]
2022/10/14 20:59:41 Use any available volume to install, volume=[/volume1]
2022/10/14 20:59:42 Use given volume to install, volume=[]
2022/10/14 20:59:42 Use any available volume to install, volume=[/volume1]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin preinst
2022/10/14 20:59:43 install nzbdrone 20210717-19 End preinst ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/mkdir -p /volume1/@appstore/nzbdrone -m 755
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/mkdir -p /volume1/@appstore/nzbdrone -m 755 ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/rm -rf /volume1/@appstore/nzbdrone
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/rm -rf /volume1/@appstore/nzbdrone ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/package /volume1/@appstore/nzbdrone
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/package /volume1/@appstore/nzbdrone ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/mkdir -p /var/packages/nzbdrone -m 755
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/mkdir -p /var/packages/nzbdrone -m 755 ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/touch /var/packages/nzbdrone/installing
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/touch /var/packages/nzbdrone/installing ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/INFO /var/packages/nzbdrone/INFO
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/INFO /var/packages/nzbdrone/INFO ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone/scripts
2022/10/14 20:59:43 install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone/scripts ret=[0]
2022/10/14 20:59:43 install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/scripts /var/packages/nzbdrone/scripts
2022/10/14 20:59:44 install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/scripts /var/packages/nzbdrone/scripts ret=[0]
2022/10/14 20:59:44 install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone/WIZARD_UIFILES
2022/10/14 20:59:44 install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone/WIZARD_UIFILES ret=[0]
2022/10/14 20:59:44 install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/WIZARD_UIFILES /var/packages/nzbdrone/WIZARD_UIFILES
2022/10/14 20:59:44 install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/WIZARD_UIFILES /var/packages/nzbdrone/WIZARD_UIFILES ret=[0]
2022/10/14 20:59:44 install nzbdrone 20210717-19 Begin /bin/rm -rf /var/packages/nzbdrone/conf
2022/10/14 20:59:44 install nzbdrone 20210717-19 End /bin/rm -rf /var/packages/nzbdrone/conf ret=[0]
2022/10/14 20:59:44 install nzbdrone 20210717-19 Begin /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/conf /var/packages/nzbdrone/conf
2022/10/14 20:59:44 install nzbdrone 20210717-19 End /bin/mv -f /volume1/@tmp/synopkg/install.kmlfPO/conf /var/packages/nzbdrone/conf ret=[0]
2022/10/14 20:59:47 Acquire systemd-unit for nzbdrone when 0x0001 (ready)
2022/10/14 20:59:48 Acquire systemd-unit for nzbdrone when 0x0001 (done)
2022/10/14 20:59:48 Acquire port-config for nzbdrone when 0x0001 (ready)
2022/10/14 20:59:48 Acquire port-config for nzbdrone when 0x0001 (done)
2022/10/14 20:59:49 install nzbdrone 20210717-19 Begin postinst
2022/10/14 20:59:49 install nzbdrone 20210717-19 End postinst ret=[0]
2022/10/14 20:59:49 install nzbdrone: begin to start version 20210717-19
2022/10/14 20:59:50 Acquire port-config for nzbdrone when 0x0001 (ready)
2022/10/14 20:59:50 Acquire port-config for nzbdrone when 0x0001 (done)
2022/10/14 20:59:50 install nzbdrone 20210717-19 Begin start-stop-status start
2022/10/14 20:59:55 install nzbdrone 20210717-19 End start-stop-status start ret=[0]
2022/10/14 20:59:56 install nzbdrone: start version 20210717-19 successfully, result 0
2022/10/14 20:59:56 install nzbdrone 20210717-19 successfully
2022/10/14 21:10:42 uninstall nzbdrone: begin to stop version 20210717-19
2022/10/14 21:10:42 uninstall nzbdrone 20210717-19 Begin start-stop-status stop
2022/10/14 21:10:43 uninstall nzbdrone 20210717-19 End start-stop-status stop ret=[0]
2022/10/14 21:10:43 Release port-config for nzbdrone when 0x0004 (ready)
2022/10/14 21:10:43 Release port-config for nzbdrone when 0x0004 (done)
2022/10/14 21:10:44 uninstall nzbdrone: stop version 20210717-19 successfully, result 0
2022/10/14 21:10:44 uninstall nzbdrone 20210717-19 Begin preuninst
2022/10/14 21:10:44 uninstall nzbdrone 20210717-19 End preuninst ret=[0]
2022/10/14 21:10:44 Release systemd-unit for nzbdrone when 0x0004 (ready)
2022/10/14 21:10:44 Release systemd-unit for nzbdrone when 0x0004 (done)
2022/10/14 21:10:45 uninstall nzbdrone 20210717-19 Begin /bin/rm -rf /volume1/@appstore/nzbdrone
2022/10/14 21:10:45 uninstall nzbdrone 20210717-19 End /bin/rm -rf /volume1/@appstore/nzbdrone ret=[0]
2022/10/14 21:10:45 uninstall nzbdrone 20210717-19 Begin /bin/rm -rf /volume1/@apptemp/nzbdrone
2022/10/14 21:10:45 uninstall nzbdrone 20210717-19 End /bin/rm -rf /volume1/@apptemp/nzbdrone ret=[0]
2022/10/14 21:10:45 Release port-config for nzbdrone when 0x0004 (ready)
2022/10/14 21:10:45 Release port-config for nzbdrone when 0x0004 (done)
2022/10/14 21:10:45 uninstall nzbdrone 20210717-19 Begin postuninst
2022/10/14 21:10:45 uninstall nzbdrone 20210717-19 End postuninst ret=[0]
2022/10/14 21:10:46 uninstall nzbdrone: Uninstall 20210717-19 successfully
```

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This replaces #5511 which built on the work from #5485 to address a number of issues in Sonarr as discussed in https://github.com/SynoCommunity/spksrc/pull/5471#issuecomment-1317381973 and summarised below:

1. Update package name to 'Sonarr v3'
2. Upgrade to Sonarr 3.0.9.1549
3. Avoid Sonarr downgrade on package update
4. Fix usage of TMPDIR and remove obsolete folders
5. Remove support for legacy (v2) versions

Fixes #5450, Closes #5471

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [x] Package update
- [x] includes a small framework change: include the STATUS (i.e. INSTALL, UPGRADE, UNINSTALL) in the installer log line created for each step

### CODE REVIEW

**Comment by mreid-tt** [comment]
Hey @hgy59, continuing the conversation here:

> Your can create a branch at the latest commit that is in sync with the upstream master.
> Then cherry pick all your commits on your master branch related to this PR
> and finally reset your master to the latests commit of upstream master.

All done!

> @mreid-tt please can you test the Lidarr approach with sonarr? unfortunately the `update_required` file is not deleted in Lidarr when updating with the current version of #5514 😖

I've implemented the concept in this new PR and the upgrade did in fact retain the existing `config.xml` post-upgrade. The detailed log from `/var/log/packages/nzbdrone.log` is captured here: https://pastebin.com/kgGH5C9L

One thing I noted however when searching for 'config.xml' files following a complete uninstall of Sonarr is that there were still some present here:

```
~$ sudo find / -name config.xml
/tmp/sonarr_backup/config.xml
/tmp/sonarr_update/sonarr_appdata_backup/config.xml
```

The backup folder does seem to be in the wrong place for a DSM7 deployment, what do you think may be causing this? Here's the detailed uninstall log in case it will help: https://pastebin.com/XrPiU8X7

> define a `validate_preinst` function in `service-setup.sh` in this function evaluate the installed version for version 2.x output and error text with echo and finally call `exit 1` otherwise do nothing.

I've included this in the PR, do let me know if the implementation is okay.

**Comment by hgy59** [comment]
> One thing I noted however when searching for 'config.xml' files following a complete uninstall of Sonarr is that there were still some present here:
> 
> ```
> ~$ sudo find / -name config.xml
> /tmp/sonarr_backup/config.xml
> /tmp/sonarr_update/sonarr_appdata_backup/config.xml
> ```

@mreid-tt 

This might be fixed with `USE_ALTERNATE_TMP_DIR = 1`
If the package regards the `TMPDIR` variable of the environment, then it will not use `/tmp` folder.
On DSM 7, it will use `/volume{n}/@apptemp/{packagename}` instead
On DSM <7, it will use `/var/packages/{packagename}/tmp` that our generic installer will create on installation and remove on uninstall.

So we have to validate, whether sonarr is using the `TMPDIR` variable or we must use another variable...

**Comment by hgy59** [comment]
@mreid-tt TODO update `spk/sonarr3/Makefile` to depend on `cross/sonarr3` (not `cross/sonarr`)

**Comment by mreid-tt** [comment]
> @mreid-tt This might be fixed with `USE_ALTERNATE_TMP_DIR = 1` If the package regards the `TMPDIR` variable of the environment, then it will not use `/tmp` folder. On DSM 7, it will use `/volume{n}/@apptemp/{packagename}` instead On DSM <7, it will use `/var/packages/{packagename}/tmp` that our generic installer will create on installation and remove on uninstall.

I believe the code is already there:
https://github.com/SynoCommunity/spksrc/blob/da38c9fda92af9ef797cfcf929c18a810ea352ba/spk/sonarr3/Makefile#L39

> So we have to validate, whether sonarr is using the `TMPDIR` variable or we must use another variable...

I've checked all the files in `cross/sonarr3` and `spk/sonarr3` and I can't seem to find a declaration for `TMPDIR`. What am I missing?

> @mreid-tt TODO update `spk/sonarr3/Makefile` to depend on `cross/sonarr3` (not `cross/sonarr`)

Thanks, saw the build error and fixed this too.

**Comment by hgy59** [comment]
> I've checked all the files in `cross/sonarr3` and `spk/sonarr3` and I can't seem to find a declaration for `TMPDIR`. What am I missing?

Is is missing (should be defined in installed script/service-setup)
You must define `USE_ALTERNATE_TMP_DIR = 1` in Makefile above the line `include ../../mk/spksrc.spk.mk`

File: spk/sonarr3/src/service-setup.sh [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+validate_preinst ()
+{
+    # use install_log to write to installer log file.
+    install_log "validate_preinst ${SYNOPKG_PKG_STATUS}"
+
+    # check if the installed distribution is a legacy version
+    if [ -f "${SYNOPKG_PKGDEST}/share/NzbDrone/NzbDrone.exe" ]; then
+        # v2 installed
+        exit 1
+    fi
```
Comment (hgy59) [inline spk/sonarr3/src/service-setup.sh:37]: see #5520 for my comment to output an error text to the user.

File: spk/sonarr3/src/service-setup.sh [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+    if [ "${SYNOPKG_DSM_VERSION_MAJOR}" -lt 7 ]; then
+        set_unix_permissions "${SYNOPKG_PKGDEST}/share"
+        # If backup was created before new-style packages
+        # new updates/backups will fail due to permissions (see #3185)
+        if [ -d "/tmp/nzbdrone_backup" ] || [ -d "/tmp/nzbdrone_update" ] || [ -d "/tmp/sonarr_backup" ] || [ -d "/tmp/sonarr_update" ]; then
+            set_unix_permissions "/tmp/nzbdrone_backup"
+            set_unix_permissions "/tmp/nzbdrone_update"
+            set_unix_permissions "/tmp/sonarr_backup"
+            set_unix_permissions "/tmp/sonarr_update"
+        fi
```
Comment (hgy59) [inline spk/sonarr3/src/service-setup.sh:90]: we probably must move these folders to the new TMPDIR

An updated comment would be like:
# Move backup folders created before alternate TMPDIR is used

Comment (mreid-tt) [reply spk/sonarr3/src/service-setup.sh:90]: I'm not sure what to do here. Should we be checking for these folders and just dumping them? Because wouldn't the backup folders adhere to the new locations created in `service_preupgrade` with the fix for the `USE_ALTERNATE_TMPDIR` you gave above?

**Comment by hgy59** [comment]
@mreid-tt Sonarr Status of v3.0.9.1549 shows an error:
`Currently installed Mono version 5.8.0.108 is no longer supported. Please upgrade Mono to version 5.20.`

If the mono certificate issues are solved, we should update the SPK_DEPENDS at least to mono>=5.20.

**Comment by hgy59** [comment]
@mreid-tt I can confirm, that on DSM 6 with ALTERNATE_TMPDIR fixed, sonarr creates the backup in the folder
```
/var/packages/nzbdrone/target/tmp/sonarr_backup
```

**Comment by hgy59** [comment]
@mreid-tt regarding the mono certificate (and mono DSM 7) issues.
I propose to create and install a script that does what you summarized in https://github.com/SynoCommunity/spksrc/issues/5051#issuecomment-1009758625.

This script could then be run (as root) with a task in DSM. The task could be executed on demand (or at DSM boot-up) and will avoid the need of an ssh login.

I prefer to add such a script to the mono package (there is still a pending PR #4669)

File: spk/sonarr3/src/service-setup.sh (hunk 2 above)
Comment (mreid-tt) [reply spk/sonarr3/src/service-setup.sh]: @hgy59, I've pushed a new commit. Let me know if this is what you were considering as a solution.

Comment (hgy59) [reply spk/sonarr3/src/service-setup.sh]: > @hgy59, I've pushed a new commit. Let me know if this is what you were considering as a solution.

@mreid-tt 
to answer your question I have added some commits.

My finding was, that those folders in /tmp are really temporary and just can be removed.
- The *_backup folder is temp. for the backup. The final backup file(s) (*.zip) are stored in the config dir under Backup and are available for download in the sonarr web UI.
- The *_update folder is used to download and extract updates. It is obsolete after the update

And I reverted to mono>=5.8 since there are issues with 5.20 and aarch64 on DSM 6 (built with DSM 6 toolchain).

**Comment by hgy59** [comment]
@mreid-tt I updated the display name to "Sonarr v3". Hopefully this clarifies that it is independent of the folders named `sonarr3`.

BTW we could use the display name "Sonarr v4" in #5520.

File: spk/sonarr3/Makefile [hunk 3]
```diff
@@ -1,30 +1,30 @@
...
 DESCRIPTION_FRE = Sonarr est un PVR pour les utilisateurs de groupes de discussion et torrents. Il peut surveiller plusieurs flux RSS pour les nouveaux épisodes de vos séries préférées et saisira, sortes et les renomme. Il peut également être configuré pour mettre à jour automatiquement la qualité des fichiers déjà téléchargés si un meilleur format de qualité devient disponible.
 DESCRIPTION_SPN = Sonarr es un PVR para los usuarios de grupos de noticias y torrents. Se puede controlar múltiples canales RSS para nuevos episodios de sus programas favoritos y se agarra, tipo y les cambia el nombre. También puede ser configurado para actualizar automáticamente la calidad de los archivos ya descargados si un formato de mejor calidad disponible.
-DISPLAY_NAME = Sonarr
+DISPLAY_NAME = Sonarr v3
 STARTABLE = yes
-CHANGELOG = "Enlarge the service start/stop timeout to 90 seconds."
+CHANGELOG = "1. Update package name to 'Sonarr v3'.<br>2. Upgrade to Sonarr 3.0.9.1549.<br/>3. Enlarge the service start/stop timeout to 90 seconds.<br>4. Avoid Sonarr downgrade on package update.<br>5. Fix usage of TMPDIR."
```
Comment (hgy59) [inline spk/sonarr3/Makefile:19]: I rearranged the order of the changelogs upon importance (IMHO).

**Comment by mreid-tt** [comment]
> BTW we could use the display name "Sonarr v4" in #5520.

Will do.

File: spk/sonarr3/src/config.xml [hunk 4]
```diff
@@ -0,0 +1,7 @@
+<?xml version="1.0" encoding="utf-8" standalone="yes"?>
```
Comment (hgy59) [inline spk/sonarr3/src/config.xml:1]: Just a small suggestion. There is no <?xml> tag after sonarr has updated this file. So we can firmly remove this line.
```suggestion
```

File: spk/sonarr3/src/service-setup.sh [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+        echo "Update from NzbDrone (Sonarr v2.x) is not supported."
+        exit 1
+    fi
+}
+
+service_postinst ()
+{
+    echo "Set update required"
+    # Make Sonarr do an update check on start to avoid possible Sonarr
+    # downgrade when synocommunity package is updated
```
Comment (hgy59) [inline spk/sonarr3/src/service-setup.sh:42]: As we now save and restore the current installation, this comment is outdated. Propose to comment like this:
```suggestion
    # Make Sonarr do an update check on start to update to the latest version available
```

**Comment by hgy59** [comment]
> @hgy59, any further changes before this is merged and published?

added two minor proposals (none of them touches the functionality of this package)

**Comment by mreid-tt** [comment]
> added two minor proposals (none of them touches the functionality of this package)

Nice! I've squashed all the Sonarr changes together as one and I've left the explicit framework change separate for visibility. Let me know if you need anything else.
