### PR TITLE
tt-rss: updated 20201114

### LINKED ISSUE #3678: Update Tiny Tiny RSS
It would be great if someone could update the Tiny Tiny RSS app (https://synocommunity.com/package/tt-rss) to the latest version.
Currently the version is from 2016 (v20160102-10).
There are a few bugs that need fixing:
https://github.com/SynoCommunity/spksrc/issues/2217
https://www.synology-forum.de/showthread.html?96698-Einrichtung-von-Tiny-Tiny-RSS/page2

### LINKED ISSUE #4231: tt-rss fails to start after update
_For new Package Requests, see the guidelines_  

### Setup
Package Name: tt-rss
Package Version: 20200829-12 

NAS Model: DS916+
NAS Architecture: x86_64 (INTEL Pentium N3710)
DSM version: DSM 6.2.3-25426 Update 2

### Expected behavior
should start and run :)

### Actual behavior
Logged in DSM I click on start. The screen shows up which shows that the app is starting. Once this window disappears the button shows again "auführen" (german for launch)

### Steps to reproduce
_1._  update your tt-rss to 20200829-12 via package manager

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
``` there is just a tt-rss.pid
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2020-10-20T12:51:06+02:00 JAS synoscgi_SYNO.Core.Package.Installation_1_install[19340]: resource_api.cpp:190 Acquire php70 for tt-rss when 0x0002 (done)
2020-10-20T12:51:06+02:00 JAS synoscgi_SYNO.Core.Package.Installation_1_install[19340]: resource_api.cpp:190 Acquire php56 for tt-rss when 0x0002 (done)
2020-10-20T12:51:06+02:00 JAS synoscgi_SYNO.Core.Package.Installation_1_install[19340]: resource_api.cpp:190 Acquire php70 for tt-rss when 0x0002 (done)
2020-10-20T12:51:06+02:00 JAS synoscgi_SYNO.Core.Package.Installation_1_install[19340]: resource_api.cpp:190 Acquire php56 for tt-rss when 0x0002 (done)
2020-10-20T18:04:46+02:00 JAS synoscgi_SYNO.Core.Package.Control_1_start[17269]: resource_api.cpp:289 Release php56 for tt-rss when 0x0008 (done)

2020/08/17 02:10:51 stop tt-rss: begin to stop version 20160102-10
2020/08/17 02:10:52 stop tt-rss 20160102-10 Begin start-stop-status stop
2020/08/17 02:10:53 stop tt-rss 20160102-10 End start-stop-status stop ret=[0]
2020/08/17 02:10:53 stop tt-rss 20160102-10 Begin unload apparmor
2020/08/17 02:10:53 stop tt-rss 20160102-10 End unload apparmor ret=[0]
2020/08/17 02:10:53 stop tt-rss: stop version 20160102-10 successfully, result 0

```

### PR DESCRIPTION
**Pull request by smaarn**
_Motivation:_  Various improvements on the tt-rss package (cleanup) + upgrade to latest version
_Linked Issue:- Closes #3678 and should close #4231

Updated tt-rss to 67f02e2aa7
Added explicit installation / upgrade message about the PHP extensions requirements.
Added explicit dependency on WebStation SPK
Added more logs to ease troubleshooting
Added: the schema upgrade process is now automatically run when upgrading
Fixed: added missing logs dir and tt-rss-daemon scripts
Fixed: invalid installation script was no longer creating db
Removed useless .htaccess logics
Reworked scripts to avoid relying on /usr/local linkage.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

File: spk/tt-rss/Makefile [hunk 1]
```diff
@@ -33,7 +36,7 @@ POST_STRIP_TARGET = tt-rss_extra_install
 BUSYBOX_CONFIG = daemon nice
 ENV += BUSYBOX_CONFIG="$(BUSYBOX_CONFIG)"
 
-PHP_EXTENSIONS = curl gd intl mysql mysqli pdo_mysql posix
+PHP_EXTENSIONS = curl gd intl mysqli pdo_mysql posix
```
Comment (smaarn) [inline spk/tt-rss/Makefile:39]: It seems that `mysql` extension is no longer available in PHP 7+ versions.

File: spk/tt-rss/Makefile [hunk 2]
```diff
@@ -48,16 +51,18 @@ $(STAGING_DIR)/etc/php/conf.d/com.synocommunity.tt-rss.ini:
...
+$(STAGING_DIR)/etc/extensions: 
+	@$(MSG) Generating $@
+	$(create_target_dir)
+	$(foreach extension,$(PHP_EXTENSIONS),echo "$(extension)" >> $@;)
+
 .PHONY: tt-rss_extra_install
-tt-rss_extra_install: $(STAGING_DIR)/etc/php/conf.d/com.synocommunity.tt-rss.ini
+tt-rss_extra_install: $(STAGING_DIR)/etc/php/conf.d/com.synocommunity.tt-rss.ini $(STAGING_DIR)/etc/extensions
 	install -m 755 -d $(STAGING_DIR)/var
+	install -m 755 -d $(STAGING_DIR)/var/logs
```
Comment (smaarn) [inline spk/tt-rss/Makefile:62]: So that we don't need to create that folder upon installation

File: spk/tt-rss/Makefile [hunk 3]
```diff
@@ -48,16 +51,18 @@ $(STAGING_DIR)/etc/php/conf.d/com.synocommunity.tt-rss.ini:
 	$(create_target_dir)
 	$(foreach extension,$(PHP_EXTENSIONS),echo "extension=$(extension).so" >> $@;)
 
+$(STAGING_DIR)/etc/extensions:
```
Comment (smaarn) [inline spk/tt-rss/Makefile:54]: I believe this can be removed

File: spk/tt-rss/src/bin/settings.sh [hunk 4]
```diff
@@ -12,5 +12,152 @@ fi
...
+    LOGS_DIR="${INSTALL_DIR}/var/logs"
+fi
+
+if [ -z "${WEB_DIR}" ]
+then
+    WEB_DIR="/var/services/web"
+fi
+
+LOG_FILE="${LOGS_DIR}/${PACKAGE}.log"
+if [ ! -f "${LOG_FILE}" ]
```
Comment (smaarn) [inline spk/tt-rss/src/bin/settings.sh:29]: Force the log file creation and ensure it's created with the appropriate owners and rights.

File: spk/tt-rss/src/conf/resource [hunk 5]
```diff
@@ -10,17 +10,5 @@
 			"relpath": "etc/php/conf.d/com.synocommunity.tt-rss.ini",
 			"destpath": "/usr/local/etc/php70/conf.d"
 		}]
-    },
```
Comment (smaarn) [inline spk/tt-rss/src/conf/resource:13]: Those workers actually don't exist.

File: spk/tt-rss/src/dsm-control.sh [hunk 6]
```diff
@@ -5,81 +5,23 @@ PACKAGE="tt-rss"
...
 PATH="${INSTALL_DIR}/bin:${PATH}"
-BUILDNUMBER="$(/bin/get_key_value /etc.defaults/VERSION buildnumber)"
-USER="$([ "${BUILDNUMBER}" -ge "4418" ] && echo -n http || echo -n nobody)"
+USER="http"
 
-TTRSS="${WEB_DIR}/${PACKAGE}/update.php"
-HT_ACCESS_FILE="${WEB_DIR}/${PACKAGE}/.htaccess"
 PID_FILE="${INSTALL_DIR}/var/tt-rss.pid"
-HT_ACCESS_SECTION_DELIMITER="#Synology PHP"
-
```
Comment (smaarn) [inline spk/tt-rss/src/dsm-control.sh:18]: This section was actually useless since WebStation enforces it using the profile mechanisms.

File: spk/tt-rss/src/dsm-control.sh [hunk 7]
```diff
@@ -5,81 +5,23 @@ PACKAGE="tt-rss"
...
 {
-    source "${INSTALL_DIR}/bin/php-settings.sh"
-    if [ ! -z "${php_fpm}" ]
-    then
-        echo "$(regenerate_htaccess ${php_fpm})" >"${HT_ACCESS_FILE}"
-    fi
-    start-stop-daemon -S -q -m -b -N 10 -x "${php}" \
+    start-stop-daemon -S -q -m -b -N 10 -a /bin/bash \
         -c ${USER} -u ${USER} -p ${PID_FILE} --  \
-        -c "${php_configuration_file}" $(php-options) \
```
Comment (smaarn) [inline spk/tt-rss/src/dsm-control.sh:75]: Moved all this into the tt-rss-daemon script.

File: spk/tt-rss/src/installer.sh [hunk 8]
```diff
@@ -103,13 +112,13 @@ preuninst ()
     # Stop the package
     ${SSS} stop > /dev/null
 
-    exit 0
+    return 0
```
Comment (smaarn) [inline spk/tt-rss/src/installer.sh:115]: Replaced those by return clauses.

**Comment by smaarn** [comment]
Binaries were uploaded here (for those who don't want to go through downloading all the packages archive generated by the checks): https://github.com/smaarn/spksrc/releases/tag/tt-rss-20201114

File: spk/tt-rss/Makefile [hunk 9]
```diff
@@ -51,13 +54,11 @@ $(STAGING_DIR)/etc/php/conf.d/com.synocommunity.tt-rss.ini:
 .PHONY: tt-rss_extra_install
 tt-rss_extra_install: $(STAGING_DIR)/etc/php/conf.d/com.synocommunity.tt-rss.ini
 	install -m 755 -d $(STAGING_DIR)/var
+	install -m 755 -d $(STAGING_DIR)/var/logs
 	install -m 755 -d $(STAGING_DIR)/app
 	install -m 644 src/app/config $(STAGING_DIR)/app/config
-	install -m 755 src/bin/guess-php-fpm-bin $(STAGING_DIR)/bin/guess-php-fpm-bin
```
Comment (smaarn) [inline spk/tt-rss/Makefile:56]: All of those files were turned into functions defined in the `settings.sh` file.

File: spk/tt-rss/Makefile (hunk 1 above)
Comment (smaarn) [reply spk/tt-rss/Makefile:39]: (and it seems it wasn't really required anyway :) )

**Comment by smaarn** [comment]
Latest binaries published here: https://github.com/smaarn/spksrc/releases/tag/tt-rss-20201114-rc2

**Comment by ymartin59** [comment]
Great. These PHP support scripts may be interesting for other packages (I think about NextCloud for instance) and may be worth to be collected in framework makefiles.

File: spk/tt-rss/Makefile [hunk 10]
```diff
@@ -12,7 +12,10 @@ DESCRIPTION_FRE = Tiny Tiny RSS est un agrégateur et lecteur web de flux RSS et
 ADMIN_URL = /tt-rss/
 RELOAD_UI = yes
 DISPLAY_NAME = Tiny Tiny RSS
-CHANGELOG = "Update Tiny Tiny RSS to Git revision 67f02e2aa7 (20200829)"
+CHANGELOG = "
+CHANGELOG += 13. Update Tiny Tiny RSS to Git revision 328d7b55c8 (20201114), add troubleshooting logs generation & fixed rights issue with upgrading on a live installation<br />
+CHANGELOG += 12. Update Tiny Tiny RSS to Git revision 67f02e2aa7 (20200829)<br />
+CHANGELOG += "
```
Comment (hgy59) [inline spk/tt-rss/Makefile:18]: The changelog numbering is proposed to start at "1." within each SPK_REV.
And it should contain entries for the dedicated SPK_REV only.
So you can ommit the numbering and the entry starting with 12.

File: spk/tt-rss/Makefile [hunk 11]
```diff
@@ -13,8 +13,9 @@ ADMIN_URL = /tt-rss/
 RELOAD_UI = yes
 DISPLAY_NAME = Tiny Tiny RSS
 CHANGELOG = "
-CHANGELOG += 13. Update Tiny Tiny RSS to Git revision 328d7b55c8 (20201114), add troubleshooting logs generation & fixed rights issue with upgrading on a live installation<br />
-CHANGELOG += 12. Update Tiny Tiny RSS to Git revision 67f02e2aa7 (20200829)<br />
+CHANGELOG += 1. Update Tiny Tiny RSS to Git revision 328d7b55c8 (20201114).<br />
+CHANGELOG += 2. add troubleshooting logs generation.<br />
+CHANGELOG += 3. fixed rights issue occurring when upgrading on a live installation.<br />
```
Comment (hgy59) [inline spk/tt-rss/Makefile:18]: please use `permission issue` here (or maybe `access rights issue`) to clarify

**Review by ymartin59 — APPROVED** [review]
LGTM
