### PR TITLE
[WIP] Add zap2epg TV grabber to tvheadend

### LINKED ISSUE #4678: Add requests to python3 package
### Setup
_Package Name:_ python3/python38

_NAS Model:_ 918+
_NAS Architecture:_  apollolake (x86_64)
_DSM version:_ 6.2.3

### Expected behavior
Using an EPG grabber in python I'm getting the following error:
```
ModuleNotFoundError: No module named 'requests'
```

### Actual behavior
It work on my default Ubuntu setup but fails under Synology DSM

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  TVH lacks of built-in TV grabber as the XMLTV project is pretty much all using perl with target compiled CPAN modules making cross-build not sustainable with the framework.  Changes in this PR incorporate zap2epg python EPG grabber directly to TVH.  This allows using built-in routine tasks from TVH without needing additional cron jobs.
_Linked issues:_  Superseeds previous `zap2it` standalone package #4608 and include `requests` python wheels which closes #4678

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### Notes
- Currently pending the merge upstream of https://github.com/edit4ever/script.module.zap2epg/pull/37

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 I thought it was that easy of adding a `WHEELS` section to the spk to get the python `requests` library to work.

I'm still getting `ModuleNotFoundError: No module named 'requests'`.
Installer log file is relatively useless:
```
# cat tvheadend_install.log 
Tue Jun 15 16:27:47 EDT 2021
===> Step preuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Tue Jun 15 16:27:51 EDT 2021
===> Step postuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
```

Advices/pointers to solve this would be much appreciated...
(now thinking, does it install python wheels only at install time or also during upgrades?)

File: spk/tvheadend/Makefile [hunk 1]
```diff
@@ -14,7 +14,7 @@ DSM_UI_DIR = app
 export TVH_VERS
 
 DEPENDS = cross/busybox cross/$(SPK_NAME) cross/zap2epg
-WHEELS = requests
+WHEELS = certifi chardet requests urllib3
```
Comment (hgy59) [inline spk/tvheadend/Makefile:17]: please use a requirements.txt file for the wheels 
and pin there each package to an explicit version

File: spk/tvheadend/src/service-setup.sh [hunk 2]
```diff
@@ -42,6 +47,18 @@ service_postinst ()
     $BIN/busybox --install $BIN
     $BIN/delgroup "${USER}" "users" >> ${INST_LOG}
     $BIN/deluser "${USER}" >> ${INST_LOG}
```
Comment (hgy59) [inline spk/tvheadend/src/service-setup.sh:49]: this is old dsm5->dsam6 migration stuff and can be removed (we do not support dsm5->dsm6 migration anymore).

and dependency to busybox can be removed

File: spk/tvheadend/src/service-setup.sh [hunk 3]
```diff
@@ -42,6 +47,18 @@ service_postinst ()
...
+
+    # EPG Grabber (zap2epg) - Create a Python virtualenv
+    ${VIRTUALENV} --system-site-packages ${PYTHONENV} >> ${INST_LOG}
+
+    # EPG Grabber (zap2epg) - Install the wheels/requirements
+    ${SYNOPKG_PKGDEST}/env/bin/pip install \
+             --no-deps --no-index --no-input --upgrade \
+             --force-reinstall --find-links \
+             ${WHEELHOUSE} ${WHEELHOUSE}/*.whl >> ${INST_LOG}  2>&1
```
Comment (hgy59) [inline spk/tvheadend/src/service-setup.sh:58]: `>> ${INST_LOG}` is not supported anymore and must be removed. All output (stdout and stderr) goes to the installer log.

```suggestion
    ${VIRTUALENV} --system-site-packages ${PYTHONENV}

    # EPG Grabber (zap2epg) - Install the wheels/requirements
    ${SYNOPKG_PKGDEST}/env/bin/pip install \
             --no-deps --no-index --no-input --upgrade \
             --force-reinstall --find-links \
             ${WHEELHOUSE} ${WHEELHOUSE}/*.whl
```

File: spk/tvheadend/Makefile [hunk 4]
```diff
@@ -14,7 +14,7 @@ DSM_UI_DIR = app
...
 SPK_DEPENDS = "python3>=3.7"
```
Comment (hgy59) [inline spk/tvheadend/Makefile:18]: as python38 is used in service setup (and use DEPENDS = `cross/python38` in  cross/tvheadend/Makefile).
```suggestion
SPK_DEPENDS = "python38"
```

File: spk/tvheadend/src/service-setup.sh [hunk 5]
```diff
@@ -2,7 +2,12 @@
 # Sourced script by generic installer and start-stop-status scripts
 
 # Add ffmpeg and ifself to path
-PATH="${SYNOPKG_PKGDEST}/bin:/var/packages/ffmpeg/target/bin:${PATH}"
+PYTHON_DIR="/var/packages/python38/target"
+PYTHONENV="${SYNOPKG_PKGDEST}/env"
+VIRTUALENV="${PYTHON_DIR}/bin/virtualenv"
+WHEELHOUSE=${SYNOPKG_PKGDEST}/share/wheelhouse
+FFMPEG_DIR="/usr/local/ffmpeg"
```
Comment (hgy59) [inline spk/tvheadend/src/service-setup.sh:9]: `/usr/local/{package}` folders must be avoid for DSM7 compatibility.

```suggestion
FFMPEG_DIR="/var/packages/ffmpeg/target"
```

File: spk/tvheadend/src/service-setup.sh [hunk 6]
```diff
@@ -42,6 +47,18 @@ service_postinst ()
...
+    ${VIRTUALENV} --system-site-packages ${PYTHONENV} >> ${INST_LOG}
+
+    # EPG Grabber (zap2epg) - Install the wheels/requirements
+    ${SYNOPKG_PKGDEST}/env/bin/pip install \
+             --no-deps --no-index --no-input --upgrade \
+             --force-reinstall --find-links \
+             ${WHEELHOUSE} ${WHEELHOUSE}/*.whl >> ${INST_LOG}  2>&1
+
+    # EPG Grabber (zap2epg) - Adjust permissions
+    set_unix_permissions "${PYTHONENV}"
```
Comment (hgy59) [inline spk/tvheadend/src/service-setup.sh:61]: If package does not run without this, you must adjust permissions for DSM<7 only.

**Review by hgy59 — CHANGES_REQUESTED** [review]
please update some outdated files.

File: spk/tvheadend/src/service-setup.sh (hunk 2 above)
Comment (th0ma7) [reply spk/tvheadend/src/service-setup.sh:49]: Changes already present in #4545

File: spk/tvheadend/src/service-setup.sh (hunk 6 above)
Comment (th0ma7) [reply spk/tvheadend/src/service-setup.sh]: There actually was no need for that ... removed.

File: spk/tvheadend/Makefile (hunk 1 above)
Comment (th0ma7) [reply spk/tvheadend/Makefile]: done.

**Comment by th0ma7** [comment]
PR pending merge of https://github.com/edit4ever/script.module.zap2epg/pull/37 to confirm download URL.

**Comment by th0ma7** [comment]
> please update some outdated files.

Thnx for the review @hgy59, much appreciated.  As mentionned some of the changes requested are already present in PR #4545.

**Review by hgy59 — APPROVED** [review]

File: cross/zap2epg/Makefile [hunk 7]
```diff
@@ -0,0 +1,26 @@
+PKG_NAME = zap2epg
+PKG_VERS = 3.0
+PKG_EXT = tar.gz
+#PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
```
Comment (hgy59) [inline cross/zap2epg/Makefile:4]: leftover

File: cross/zap2epg/Makefile [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+
+HOMEPAGE = https://github.com/edit4ever/script.module.zap2epg
+COMMENT  = zap2epg will generate an xmltv.xml file for USA/Canada TV lineups using zap2it source
+LICENSE  = GPLv3
+
+INSTALL_TARGET = zap2it_install
+
+include ../../mk/spksrc.install-resources.mk
+
+.PHONY: zap2it_install
```
Comment (hgy59) [inline cross/zap2epg/Makefile:21]: replace `zap2it` by `zap2epg`

**Comment by hgy59** [comment]
sorry my latest review is too late...

**Comment by th0ma7** [comment]
> sorry my latest review is too late...

@hgy59 never too late!  I'll port it over to #4686
