### PR TITLE
syncthing: update to v1.23.4 and include next-gen-gui

### LINKED ISSUE #5289: Syncthing: accept: function not implemented
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Syncthing

### Package Version

1.20.0-26

### Device Model

DS413j

### Device Architecture

ARMv5

### Firmware Version

DSM 6.2.4-25556

### What happened?

I noticed that Syncthing's log was continiously saying that `accept: not implemented`. Missing dependencies or something?

### Reproduction steps

```bash
1. Install Syncthing
2. `tail -f .../@appstore/syncthing/var/syncthing.log`
3.
...
```

### Install Log

```log
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin preinst
2022/05/26 22:34:58     Begin reload_inst_variables
2022/05/26 22:34:58     End reload_inst_variables
2022/05/26 22:34:58     Begin initialize_variables
2022/05/26 22:34:58     End initialize_variables
2022/05/26 22:34:58     ===> Step preinst. USER=syncthing GROUP=sc-syncthing SHARE_PATH=
2022/05/26 22:34:58     install syncthing 1.20.0-26 End preinst ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/rm -rf /volume1/@appstore/syncthing
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/rm -rf /volume1/@appstore/syncthing ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/syncthing
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/syncthing ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/rm -rf /var/packages/syncthing
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/rm -rf /var/packages/syncthing ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/mkdir -p /var/packages/syncthing
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/mkdir -p /var/packages/syncthing ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/syncthing/INFO
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/syncthing/INFO ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/rm -rf /var/packages/syncthing/scripts
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/rm -rf /var/packages/syncthing/scripts ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/syncthing/scripts
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/syncthing/scripts ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/rm -rf /var/packages/syncthing/WIZARD_UIFILES
2022/05/26 22:34:58     install syncthing 1.20.0-26 End /bin/rm -rf /var/packages/syncthing/WIZARD_UIFILES ret=[0]
2022/05/26 22:34:58     install syncthing 1.20.0-26 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/syncthing/WIZARD_UIFILES
2022/05/26 22:34:59     install syncthing 1.20.0-26 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/syncthing/WIZARD_UIFILES ret=[0]
2022/05/26 22:34:59     install syncthing 1.20.0-26 Begin /bin/rm -rf /var/packages/syncthing/conf
2022/05/26 22:34:59     install syncthing 1.20.0-26 End /bin/rm -rf /var/packages/syncthing/conf ret=[0]
2022/05/26 22:34:59     install syncthing 1.20.0-26 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/syncthing/conf
2022/05/26 22:34:59     install syncthing 1.20.0-26 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/syncthing/conf ret=[0]
2022/05/26 22:35:00     install syncthing 1.20.0-26 Begin postinst
2022/05/26 22:35:00     Begin reload_inst_variables
2022/05/26 22:35:00     End reload_inst_variables
2022/05/26 22:35:01     Begin initialize_variables
2022/05/26 22:35:01     End initialize_variables
2022/05/26 22:35:01     ===> Step postinst. USER=syncthing GROUP=sc-syncthing SHARE_PATH=
2022/05/26 22:35:01     Begin save_wizard_variables
2022/05/26 22:35:01     End save_wizard_variables
2022/05/26 22:35:02     Creating group sc-syncthing
2022/05/26 22:35:08     Group Name: [sc-syncthing]
2022/05/26 22:35:08     Group Type: [AUTH_LOCAL]
2022/05/26 22:35:08     Group ID:   [65536]
2022/05/26 22:35:08     Group Members:
2022/05/26 22:35:08     0:[sc-syncthing]
2022/05/26 22:35:09     Begin service_postinst
2022/05/26 22:35:09     2022/05/26 22:35:09 INFO: Generating ECDSA key and certificate for syncthing...
2022/05/26 22:35:11     Device ID: OCBQNDH-4OCEZ5T-2PWSLX3-PXPDKHH-T5SFF4V-CIUKILJ-SQS2THX-X27S6QH
2022/05/26 22:35:11     Updated GUI authentication user name: syncthing
2022/05/26 22:35:12     Updated GUI authentication password.
2022/05/26 22:35:12     End service_postinst
2022/05/26 22:35:12     Granting 'sc-syncthing' unix ownership on /volume1/@appstore/syncthing/var
2022/05/26 22:35:12     install syncthing 1.20.0-26 End postinst ret=[0]
2022/05/26 22:35:12     install syncthing 1.20.0-26 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2022/05/26 22:35:12     install syncthing 1.20.0-26 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2022/05/26 22:35:24     install syncthing 1.20.0-26 Begin start-stop-status start
2022/05/26 22:35:24     install syncthing 1.20.0-26 End start-stop-status start ret=[0]
2022/05/27 00:46:15     (system) trigger syncthing 1.20.0-26 Begin start-stop-status stop
2022/05/27 00:46:23     (system) trigger syncthing 1.20.0-26 End start-stop-status stop ret=[0]
2022/05/27 00:50:21     (system) trigger syncthing 1.20.0-26 Begin start-stop-status start
2022/05/27 00:50:23     (system) trigger syncthing 1.20.0-26 End start-stop-status start ret=[0]
2022/05/27 02:14:42     (system) trigger syncthing 1.20.0-26 Begin start-stop-status stop
2022/05/27 02:14:46     (system) trigger syncthing 1.20.0-26 End start-stop-status stop ret=[0]
2022/05/27 12:51:21     (system) trigger syncthing 1.20.0-26 Begin start-stop-status start
2022/05/27 12:51:23     (system) trigger syncthing 1.20.0-26 End start-stop-status start ret=[0]
```

### Service Log

```log
Very, very long log. First entries are:

Begin service_prestart
End service_prestart
Starting syncthing command /volume1/@appstore/syncthing/bin/syncthing serve --home=/volume1/@appstore/syncthing/var  
[start] 2022/05/27 12:51:27 INFO: syncthing v1.20.1 "Fermium Flea" (go1.18.1 linux-arm) teamcity@build.syncthing.net 2022-05-04 16:17:03 UTC
[OCBQN] 2022/05/27 12:51:32 INFO: My ID: OCBQNDH-4OCEZ5T-2PWSLX3-PXPDKHH-T5SFF4V-CIUKILJ-SQS2THX-X27S6QH
[OCBQN] 2022/05/27 12:51:33 INFO: Single thread SHA256 performance is 0.99 MB/s using crypto/sha256 (0.41 MB/s using minio/sha256-simd).
[OCBQN] 2022/05/27 12:51:47 INFO: Hashing performance is 0.64 MB/s
[OCBQN] 2022/05/27 12:51:48 INFO: Overall send rate is unlimited, receive rate is unlimited
[OCBQN] 2022/05/27 12:51:48 INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[OCBQN] 2022/05/27 12:51:48 INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[OCBQN] 2022/05/27 12:51:48 INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[OCBQN] 2022/05/27 12:51:48 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
[OCBQN] 2022/05/27 12:51:48 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
2022/05/27 12:51:48 failed to sufficiently increase receive buffer size (was: 112 kiB, wanted: 2048 kiB, got: 224 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
[OCBQN] 2022/05/27 12:51:48 INFO: TCP listener ([::]:22000) starting
[OCBQN] 2022/05/27 12:51:48 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:51:48 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[OCBQN] 2022/05/27 12:51:48 INFO: QUIC listener ([::]:22000) starting
[OCBQN] 2022/05/27 12:51:48 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:51:48 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:51:48 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:51:48 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:51:48 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:51:48 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:51:48 INFO: My name is "DiskStation"
[OCBQN] 2022/05/27 12:51:50 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:51:52 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:51:52 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:51:52 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:51:52 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:51:52 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:51:52 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:51:56 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:51:56 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:51:56 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:51:56 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:51:56 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:51:56 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:51:56 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:52:00 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[OCBQN] 2022/05/27 12:52:00 INFO: listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": net/http: TLS handshake timeout
[OCBQN] 2022/05/27 12:52:00 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[OCBQN] 2022/05/27 12:52:00 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:52:04 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:52:07 INFO: New NAT port mapping: external TCP address 77.181.50.47:48136 to local address [::]:22000.
[OCBQN] 2022/05/27 12:52:07 INFO: Detected 1 NAT service
[OCBQN] 2022/05/27 12:52:10 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:52:15 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[OCBQN] 2022/05/27 12:52:15 INFO: listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": net/http: TLS handshake timeout
[OCBQN] 2022/05/27 12:52:15 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[OCBQN] 2022/05/27 12:52:18 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:52:18 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:52:18 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:52:18 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:52:18 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:52:18 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:52:19 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 12:52:21 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:52:21 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:52:21 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:52:21 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:52:21 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:52:23 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:52:23 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 12:52:23 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 12:52:23 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 12:52:23 INFO: GUI and API listening on [::]:8384

... 

[OCBQN] 2022/05/27 22:28:55 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:28:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:28:55 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:28:55 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:28:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:28:55 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:28:55 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:28:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:28:55 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:28:55 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:28:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:28:55 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:28:55 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:28:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:28:55 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:28:55 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:28:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:28:55 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:00 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:09 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:14 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:29:14 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:29:14 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:14 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:29:14 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:29:14 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:14 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:29:14 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:29:14 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:14 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:29:14 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:29:14 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:14 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:29:14 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:29:14 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:14 INFO: GUI and API listening on [::]:8384
[OCBQN] 2022/05/27 22:29:14 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[OCBQN] 2022/05/27 22:29:14 WARNING: GUI/API: accept tcp [::]:8384: accept: function not implemented (restarting)
[OCBQN] 2022/05/27 22:29:19 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:19 INFO: TCP listener ([::]:22000) shutting down
[OCBQN] 2022/05/27 22:29:19 INFO: listenerSupervisor@tcp://0.0.0.0:22000: service tcp://0.0.0.0:22000 failed: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:19 INFO: TCP listener ([::]:22000) starting
[OCBQN] 2022/05/27 22:29:19 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:20 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:22 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:25 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:29 WARNING: Listen (BEP/tcp): Accepting connection: accept tcp [::]:22000: accept: function not implemented
[OCBQN] 2022/05/27 22:29:29 INFO: New NAT port mapping: external TCP address 77.181.50.47:48136 to local address [::]:22000.
```

### Other Logs

_No response_

### PR DESCRIPTION
**Pull request by hgy59**
## Description

- regarding #5289 we have to wait for GO v1.19.5 to include fix for ARMv5
- update syncthing to v1.22.2
- include next-get-gui and provide it under /tech-ui
- fix parameter of ca_reloader.sh
- fix link in wizard files

Fixes #5289

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@acolomb I plan to add configuration of a shared folder to the installation wizard. This folder will be used as the default sync folder. 

Currently the package var folder is used as HOME and therefore the default sync folder (for sc-syncthing service user). As reported in #3320 this folder is not accessible by DSM users. A shared folder will be supported by DSM to configure dedicated user permissions.

I already updated syncthing in this PR to not create the default folder at first service start.

Any hint is appreciated, _as I am not a syncthing user_.

**Comment by acolomb** [comment]
Well, Syncthing doesn't have or need the concept of *one main folder*, as it can be pointed at any accessible path in the file system.  The default folder is basically just to help get people jump-started on the Desktop.  It doesn't really make sense on a NAS I think, where the purpose is usually to synchronize files which are also used by other applications or sharing protocols.

Thus the most sensible solution would be to just [disable creating the default folder](https://docs.syncthing.net/users/syncthing.html#cmdoption-no-default-folder), via `--no-default-folder` when first calling `syncthing generate` or `syncthing serve` in `service-setup.sh`.

If you want to add a "share" through the wizard, where would that be stored and how could other apps access it?  I don't see how creating an empty default folder under a new share really helps with using Syncthing on the NAS.  The default folder can be removed from Syncthing anytime, but the share will stay around, for what purpose?

File: cross/syncthing/Makefile [hunk 1]
```diff
@@ -1,27 +1,42 @@
...
 PKG_DIST_NAME = $(PKG_NAME)-source-v$(PKG_VERS).$(PKG_EXT)
 PKG_DIST_SITE = https://github.com/syncthing/syncthing/releases/download/v$(PKG_VERS)
-PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
 EXTRACT_PATH = $(WORK_DIR)/src/github.com/$(PKG_NAME)
 PKG_DIR = $(PKG_NAME)
 
-DEPENDS = native/go
+BUILD_DEPENDS = native/go
+# add node for "next gen gui"
+BUILD_DEPENDS += native/nodejs
```
Comment (acolomb) [inline cross/syncthing/Makefile:11]: Wow, is that really necessary?  I'd like to avoid blowing up the build complexity and time like that.

File: spk/syncthing/Makefile [hunk 2]
```diff
@@ -22,7 +23,7 @@ WIZARDS_DIR = src/wizard/
 SERVICE_USER = auto
 SERVICE_SETUP = src/service-setup.sh
 SERVICE_PORT = 8384
-SERVICE_PORT_TITLE = $(DISPLAY_NAME)
+SERVICE_PORT_TITLE = Syncthing GUI
```
Comment (acolomb) [inline spk/syncthing/Makefile:26]:
```suggestion
SERVICE_PORT_TITLE = Syncthing Web GUI
```

We call it `Syncthing Web GUI` in the service definition (for firewalls), better be consistent here.

File: spk/syncthing/src/ca_reloader.sh [hunk 3]
```diff
@@ -8,7 +8,7 @@ fi
 SYNCTHING=/var/packages/syncthing/target/bin/syncthing
 
 case $1 in
-    syncthing_webui)
+    syncthing-webui)
```
Comment (acolomb) [inline spk/syncthing/src/ca_reloader.sh:11]: This doesn't work because it does not match the definition in `syncthing.sc`.  There had been some discussion whether a hyphen or underscore is the correct separator, which ended in using the underscore consistently.  Please stick with that to avoid troubles during upgrades when DSM doesn't associate the same service again.

File: spk/syncthing/src/options.conf [hunk 4]
```diff
@@ -1,6 +1,9 @@
...
+# to add additional parameters to start syncthing with.
 # For possible options see syncthing --help
 
-# Example: uncomment this to start syncthing with all devices paused
-# SYNCTHING_OPTIONS="-paused"
+# Example: to start syncthing with all devices paused
+# SYNCTHING_OPTIONS="--paused"
+
+# Do not create a default folder when starting for the first time
+SYNCTHING_OPTIONS="--no-default-folder"
```
Comment (acolomb) [inline spk/syncthing/src/options.conf:9]: Good, but I'd rather have this hard-coded in `service-setup.sh` instead.  Making it configurable to the user is mostly useless, because it's only honored on first start anyway.

File: cross/syncthing/PLIST [hunk 5]
```diff
@@ -1 +1,2 @@
 bin:bin/syncthing
+rsc:gui/default/
```
Comment (acolomb) [inline cross/syncthing/PLIST:2]:
```suggestion
rsc:gui/default/tech-ui/
```

Probably doesn't change anything, but this could be misleading to think that the regular GUI will also be installed as source, while it is really only bundled in the binary.

**Review by acolomb — CHANGES_REQUESTED** [review]

File: spk/syncthing/src/ca_reloader.sh (hunk 3 above)
Comment (hgy59) [reply spk/syncthing/src/ca_reloader.sh:11]: This is only the paramerter of this script. It has no other meaning.
The usage tells that you have to call the script with the parameter "syncthing-webui" but the script worked only with the paramer "syncthing_webui".
Should I fix this the other way round? (keep the parameter syncthing_webui and fix the usage output)

File: spk/syncthing/src/options.conf (hunk 4 above)
Comment (hgy59) [reply spk/syncthing/src/options.conf:9]: I prefer this solution
- it does not touch existing installations on package update as an update does not overwrite this file
- it is the default for the configurable options on new installations, so it is active on the first start. Afterwards a user may remove this, as it is not honored anymore

File: spk/syncthing/src/ca_reloader.sh (hunk 3 above)
Comment (acolomb) [reply spk/syncthing/src/ca_reloader.sh:11]: Oh now I see. Yes, definitely the script does work and it is called by DSM with the name containing an underscore.  Please fix the usage message instead.

File: cross/syncthing/Makefile (hunk 1 above)
Comment (hgy59) [reply cross/syncthing/Makefile:11]: @acolomb don't you agree that it is worth to include the next-gen-gui?
IMHO build time doesn't matter, only package size matters and this additional gui increases the package size less than 10% (< 1 MB).

File: spk/syncthing/src/options.conf (hunk 4 above)
Comment (acolomb) [reply spk/syncthing/src/options.conf:9]: Exactly my point, it is not honored anymore.  When a user finds this config file and removes the option, they might expect a default folder to magically appear (on next restart?).  But in fact nothing will happen.  If we don't think a default folder makes sense (especially under its default location), let's disable it for good.

File: spk/syncthing/src/ca_reloader.sh (hunk 3 above)
Comment (hgy59) [reply spk/syncthing/src/ca_reloader.sh:11]: Oh no **I** see, didn't know that this script is called by DSM...

File: cross/syncthing/Makefile (hunk 1 above)
Comment (acolomb) [reply cross/syncthing/Makefile:11]: Originally the tech-ui used to be distributed as a single ZIP file, already built.  That should be dropped inside the `STGUIASSETS` dir, which is probably harder to specify in the DSM environment.  So making a path available for that is a good move, so people can drop the tech-ui or any other themes / modifications in there.  But I don't see much value in shipping the tech-gui by default, it's really more of an experiment and not well maintained.

At least not useful enough to justify the added build complexity.  E.g. on my machine, `--with-next-gen-gui` hangs somewhere in the process caused by some NPM failure I have absolutely no interest in debugging. And such a build doesn't work in my IDE's console because of NPM's colored and line-overwriting output. Many small details making life harder for simply building a Go package...

File: spk/syncthing/src/options.conf (hunk 4 above)
Comment (acolomb) [reply spk/syncthing/src/options.conf:10]: Besides my thinking that this is a confusing (for the user) way to implement it, technically it won't work either, at least when the wizard is supplied with GUI credentials.  Because `syncthing generate` is called without the `SYNCTHING_OPTIONS` appended, which is the Right Thing to do.  If that was already run, the `--no-default-folder` won't work anymore, because the config was already created during `generate`.

Comment (hgy59) [reply spk/syncthing/src/options.conf:10]: When I read the documentation, my understanging was, that the `--no-default-folder` parameter is only evaluated at the first service start (i.e. `syncthing serve` and not with `syncthing generate`), but you are the expert...
If with the parameter `--no-default-folder` something is written to the config, we might adjust the config.xml that is installed with the package and avoid the parameter at all.

Comment (acolomb) [reply spk/syncthing/src/options.conf:10]: Oh I forgot we already do ship a `config.xml` as template.  In that case, the option isn't even necessary, as the default folder is *strictly only* added when no XML file exists previously and `--no-default-folder` wasn't passed.  There is nothing to fix here really.

Comment (hgy59) [reply spk/syncthing/src/options.conf:10]: In the current config.xml the defaults section looks like this:
```xml
    <defaults>
        <folder ignorePerms="true">
        </folder>
    </defaults>
```

After syncthing is started, there is an attribute `path="~"` added to the folder tag.

For our package the HOME (~) folder is `/var/packages/syncthing/var` - that was the cause for #3320 as this folder is not accessible by users.
Shall we add  `path=""` to config.xml to disable a default path?
With this, at least, there is no default value for the folder, when adding a new folder in syncthing web gui.

The default section would be:
```xml
    <defaults>
        <folder ignorePerms="true" path="">
        </folder>
    </defaults>
```

Comment (acolomb) [reply spk/syncthing/src/options.conf:10]: Oh! I think we have a big misunderstanding here.  The XML section you quoted is used as a template when adding a new folder through the GUI or otherwise.  The `path` attribute is what gets suggested in the GUI when adding manually, or when auto-accept is enabled, new folders get created below this path.  It actually makes sense to set this to a more human-friendly (as in accessible via File Station) directory / share.

The other thing we're talking about is a "dummy" folder being created during first run *IF* the XML file does not even exist. That would be a `<folder id="default" ...` element and has nothing to do with the `<defaults><folder ...>` element.  We don't have such a dummy folder in our template config, and it won't get created anyway because we do already install the XML before first starting Syncthing.  Using `--no-default-folder` would make no difference at all.

The best solution IMHO is actually to set `$HOME` to something more sensible.  What options do we have for that?  Only by creating a share from the wizard?

Comment (hgy59) [reply spk/syncthing/src/options.conf:10]: The only option I see is to use/create a shared folder a user selects in the install wizard. This is the only supported method to create a folder with read/write access for the internal package user (sc-syncthing).
For all other folders, the users have to give permissions for the package user (with file station)
I can't see that $HOME makes any sense here.

I only want to prevent that a clumsy user takes `/var/packages/syncthing/var` as parent for folders to sync.
So I prefer to add `path=""` to defaults-folder-configuration.

PS: the only misunderstanding was that #3320 proposed to disable the default folder creation.

Comment (acolomb) [reply spk/syncthing/src/options.conf]: > PS: the misleading item was that #3320 proposed to disable the default folder creation.

Definitely :wink:

Setting `path=""` does work, but `$HOME` is still relevant, as that's what the tilde `~` expands to when entering paths. See this screenshot:
image

The same goes for the auto-accept feature. If it gets enabled for a device, the default (template) folder path will be used as a parent for any accepted folders.  So if the only way to have a sensible default location is by asking the user for a new share in the wizard, then I guess that's our best option to avoid troubles.  But we'll need to explain properly what this share is actually used for, and that any other folder can also be synced (with sufficient permissions).

**Comment by hgy59** [comment]
@acolomb I am not happy with the creation of a shared folder.
What about my solution to define a custom HOME folder on in options.conf?

File: spk/syncthing/src/ca_reloader.sh [hunk 6]
```diff
@@ -10,16 +10,16 @@ SYNCTHING=/var/packages/syncthing/target/bin/syncthing
...
+        ln -sf ${CERT_DIR}/cert.pem ${CONF_DIR}/https-cert.pem
+        ln -sf ${CERT_DIR}/privkey.pem ${CONF_DIR}/https-key.pem
 
         # Required: set $HOME environment variable
-        HOME=$CONF_DIR
+        HOME=${CONF_DIR}
         export HOME
 
-        $SYNCTHING cli --home=$CONF_DIR operations restart
+        ${SYNCTHING} cli --config=${CONF_DIR} --data=${CONF_DIR} operations restart
```
Comment (acolomb) [inline spk/syncthing/src/ca_reloader.sh:20]: This doesn't really change anything, the options are equivalent.  Is it just to avoid confusion between `$HOME` and `--home`?

File: spk/syncthing/src/service-setup.sh [hunk 7]
```diff
@@ -1,23 +1,25 @@
...
-# Required to run any syncthing command: set $HOME environment variable
-HOME=${SYNOPKG_PKGVAR}
-export HOME
-
 # include next gen gui
 export STGUIASSETS=${SYNOPKG_PKGDEST}/gui
 
 set_credentials() {
     if [ -n "${wizard_username}" -a -n "${wizard_password}" ]; then
+        echo "create user ${wizard_username} for syncthing web gui access"
```
Comment (acolomb) [inline spk/syncthing/src/service-setup.sh:16]: I find this message a bit misleading.  Normally when "creating a user", we are talking about a DSM system level user account.
```suggestion
        echo "set user name ${wizard_username} for syncthing Web GUI access"
```

**Review by acolomb — COMMENTED** [review]
I like how the HOME variable can be overridden now, but I seriously doubt anyone will use it.  The template folder path can already be adjusted directly in the Web GUI, and therefore `$HOME` is only relevant for the meaning of `~`.

I haven't tested any of this yet, just looked at the code.

File: cross/syncthing/Makefile (hunk 1 above)
Comment (acolomb) [reply cross/syncthing/Makefile:11]: Can we please get rid of this next-gen-gui stuff again?

File: spk/syncthing/src/ca_reloader.sh (hunk 6 above)
Comment (hgy59) [reply spk/syncthing/src/ca_reloader.sh:20]: Yes it is (but it is not equivalent for `syncthing generate` that does not accept the --data parameter)
I was very confused until I realized that `--home` does not define the `HOME` folder.

**Comment by acolomb** [comment]
@hgy59 This should be updated to the latest Syncthing v1.23.0 (or whatever is the latest stable) release before merging.

**Comment by acolomb** [comment]
@hgy59 I've now successfully built the package for aarch64, including the next-gen-gui, with Go 1.19.5.  It took about four minutes mainly because of all the NPM stuff going on.  Frankly I don't even know what even needs "building" there, the usual GUI just works from the Git repo state.

So I repeat my request to please leave this `--with-next-gen-gui` part out of the build and drop the NPM dependency.

If anyone wants to use the "tech-ui", it's as simple as unzipping its build to the theme folder (we can keep the introduced `gui/` subdirectory), but the build doesn't need to happen during SPK construction IMHO.  This leaves room for other drop-in themes or modified GUIs.  Actually someone is currently working on modernizing the old Web GUI, so we'll see whether that ends up needing a build step, but right now please skip it for the tech-ui.

**Comment by hgy59** [comment]
@acolomb this should be ready to merge now

**Comment by acolomb** [comment]
Let me take a look tonight or tomorrow probably.

**Comment by hgy59** [comment]
> Let me take a look tonight or tomorrow probably.

don't hurry, I will be offline for about a week. (BTW i removed the nodejs dependency by adding prebuilt tech-ui).

**Comment by hgy59** [comment]
@acolomb just a friendly reminder to have a look at this PR.

**Comment by acolomb** [comment]
Thanks @hgy59 and sorry for taking so long. I've had some unforeseen things to take care of lately so didn't get a chance to look at code. Hopefully this week.

**Comment by agoeckner** [comment]
If the "next gen UI" is a sticking point, can we please just perform an upgrade to v1.23.1?

**Comment by acolomb** [comment]
I just didn't find the time to review again, but it's not forgotten and I will try to get it done very soon.

Before we merge, v1.23.3 just came out, so better include that latest version before merging. However a bug (https://github.com/syncthing/syncthing/issues/8851) was just found which may lead to another point release in the next few days, will keep you posted on that.

Note that you should be on Syncthing v1.23.3 already if you haven't disabled the internal upgrade mechanism. The packaged binary keeps itself up to date regardless of the SPK package version.

**Comment by agoeckner** [comment]
> Note that you should be on Syncthing v1.23.3 already if you haven't disabled the internal upgrade mechanism. The packaged binary keeps itself up to date regardless of the SPK package version.

Thanks! I forgot that I had disabled the updater. All is working well now with v1.23.4 on my DS212j.

File: cross/syncthing/Makefile [hunk 8]
```diff
@@ -20,8 +19,7 @@ GO_BIN_DIR = $(GO_SRC_DIR)/$(PKG_NAME)
 
 include ../../mk/spksrc.cross-go.mk
 
-BUILD_ARGS = -goos=$(GOOS) -goarch=$(GO_ARCH) -version=v$(PKG_VERS)
-
+BUILD_ARGS  = -goos=$(GOOS) -goarch=$(GO_ARCH) -version=v$(PKG_VERS)
```
Comment (acolomb) [inline cross/syncthing/Makefile:22]: Needless whitespace change? Please revert.

File: spk/syncthing/Makefile [hunk 9]
```diff
@@ -1,18 +1,20 @@
 SPK_NAME = syncthing
-SPK_VERS = 1.22.1
-SPK_REV = 28
+SPK_VERS = 1.23.1
```
Comment (acolomb) [inline spk/syncthing/Makefile:2]:
```suggestion
SPK_VERS = 1.23.4
```

File: cross/syncthing/Makefile [hunk 10]
```diff
@@ -1,13 +1,12 @@
 PKG_NAME = syncthing
-PKG_VERS = 1.22.1
+PKG_VERS = 1.23.1
```
Comment (acolomb) [inline cross/syncthing/Makefile:2]:
```suggestion
PKG_VERS = 1.23.4
```

File: cross/syncthing/digests [hunk 11]
```diff
@@ -1,3 +1,3 @@
-syncthing-1.22.1.tar.gz SHA1 c8e0e75b0ba5b04f4f7ce8a98dcf7212733dce37
-syncthing-1.22.1.tar.gz SHA256 b024d112167e0e81a785ab98c1a044aee1ac041dfe57a62772c08284f875a5bd
-syncthing-1.22.1.tar.gz MD5 6947b7b3a1eaf03d8e6f371894c37b41
+syncthing-source-v1.23.1.tar.gz SHA1 d15101bc7e8e55dc600f56e9e634b508f6cf13a9
+syncthing-source-v1.23.1.tar.gz SHA256 d866d98e23fe6818fe97a7cb9874dc79a55d2b76af3e7bd3b37bcc8b3f62e2a2
+syncthing-source-v1.23.1.tar.gz MD5 28f33461580ea4d6391e792d66ef826e
```
Comment (acolomb) [inline cross/syncthing/digests:3]:
```suggestion
syncthing-source-v1.23.4.tar.gz SHA1 e4aead28fa927acc618d69d702a75703faa37bc0
syncthing-source-v1.23.4.tar.gz SHA256 06a2882f8ac49e15faf96025b01d0edcd4cc190a419d5de98fbe8271695329fa
syncthing-source-v1.23.4.tar.gz MD5 59280b2e551a8001ce84867c27398aa3
```

File: spk/syncthing/Makefile [hunk 12]
```diff
@@ -1,18 +1,20 @@
...
 
+# archs not supported by go
 UNSUPPORTED_ARCHS = $(PPC_ARCHS)
 
 MAINTAINER = acolomb
 DESCRIPTION = Automatically sync files via secure, distributed technology.
 DESCRIPTION_FRE = Synchronisation automatique de fichiers via une technologie sécurisée et distribuée.
 DISPLAY_NAME = Syncthing
-CHANGELOG = "1. Update syncthing to v1.22.1."
+CHANGELOG = "1. Update syncthing to v1.23.1.<br/>2. Include next gen gui (path: /tech-ui)."
```
Comment (acolomb) [inline spk/syncthing/Makefile:17]:
```suggestion
CHANGELOG = "1. Update syncthing to v1.23.4.<br/>2. Include next gen gui (path: /tech-ui)."
```

**Review by acolomb — CHANGES_REQUESTED** [review]
Looks good except for needing an upgrade to v1.23.4 now.  Suggestions included to carry that out.  Otherwise just a simple needless whitespace change.
