### PR TITLE
fix transmission (#5685)

### LINKED ISSUE #5685: Empty blocklist in Transmission 4.0.2
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Transmission

### Package Version

4.0.2-21

### Device Model

DS214se

### Device Architecture

ARMv7 (armada370)

### Firmware Version

DSM 7.1.1-42962 Update 4

### What happened?

After update to Transmission 4.0.2 blocklist is empty. Update ends with:
obraz
WebGUI also shows zero entries:
obraz

although the same list worked on 3.00-20 and currently has 88 412 entries:
obraz
(example from other devices still running Transmission 3)

I suspect it might be permissions issue but I cannot see anything in logs.
Blocklist link: https://mirror.codebucket.de/transmission/blocklist.p2p.gz

### Reproduction steps

```bash
1. Update blocklist in WebGUI
2. Nothing happens
3. WebGUI shows that blocklist has zero entries
...
```

### Install Log

```log
2023/03/30 21:34:51     upgrade transmission 3.00-20 Begin start-stop-status stop
2023/03/30 21:34:57     upgrade transmission 3.00-20 End start-stop-status stop ret=[0]
2023/03/30 21:34:59     upgrade transmission 3.00-20 Begin preupgrade
2023/03/30 21:34:59     Begin load_variables_from_file
2023/03/30 21:35:00     End load_variables_from_file
2023/03/30 21:35:00     Begin initialize_variables
2023/03/30 21:35:00     End initialize_variables
2023/03/30 21:35:00     ===> Step preupgrade. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:00     upgrade transmission 3.00-20 End preupgrade ret=[0]
2023/03/30 21:35:01     upgrade transmission 3.00-20 Begin preuninst
2023/03/30 21:35:01     Begin reload_inst_variables
2023/03/30 21:35:01     End reload_inst_variables
2023/03/30 21:35:02     Begin initialize_variables
2023/03/30 21:35:02     End initialize_variables
2023/03/30 21:35:02     ===> Step preuninst. USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:02     upgrade transmission 3.00-20 End preuninst ret=[0]
2023/03/30 21:35:02     upgrade transmission 3.00-20 Begin /bin/rm -rf /volume1/@appstore/transmission
2023/03/30 21:35:03     upgrade transmission 3.00-20 End /bin/rm -rf /volume1/@appstore/transmission ret=[0]
2023/03/30 21:35:03     upgrade transmission 3.00-20 Begin /bin/rm -rf /volume1/@apptemp/transmission
2023/03/30 21:35:03     upgrade transmission 3.00-20 End /bin/rm -rf /volume1/@apptemp/transmission ret=[0]
2023/03/30 21:35:03     upgrade transmission 3.00-20 Begin postuninst
2023/03/30 21:35:03     Begin reload_inst_variables
2023/03/30 21:35:03     End reload_inst_variables
2023/03/30 21:35:03     Begin initialize_variables
2023/03/30 21:35:04     End initialize_variables
2023/03/30 21:35:04     ===> Step postuninst. USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:04     upgrade transmission 3.00-20 End postuninst ret=[0]
2023/03/30 21:35:04     upgrade transmission 4.0.2-21 Begin preinst
2023/03/30 21:35:05     Begin load_variables_from_file
2023/03/30 21:35:05     End load_variables_from_file
2023/03/30 21:35:05     Begin initialize_variables
2023/03/30 21:35:05     End initialize_variables
2023/03/30 21:35:05     ===> Step preinst. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:05     upgrade transmission 4.0.2-21 End preinst ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mkdir -p /volume1/@appstore/transmission -m 755
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mkdir -p /volume1/@appstore/transmission -m 755 ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /volume1/@appstore/transmission
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /volume1/@appstore/transmission ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/package /volume1/@appstore/transmission
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/package /volume1/@appstore/transmission ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mkdir -p /var/packages/transmission -m 755
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mkdir -p /var/packages/transmission -m 755 ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/touch /var/packages/transmission/installing
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/touch /var/packages/transmission/installing ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/INFO /var/packages/transmission/INFO
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/INFO /var/packages/transmission/INFO ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission/scripts
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission/scripts ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/scripts /var/packages/transmission/scripts
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/scripts /var/packages/transmission/scripts ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES ret=[0]
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission/conf
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission/conf ret=[0]
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/conf /var/packages/transmission/conf
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/conf /var/packages/transmission/conf ret=[0]
2023/03/30 21:35:29     upgrade transmission 4.0.2-21 Begin postinst
2023/03/30 21:35:29     Begin load_variables_from_file
2023/03/30 21:35:29     End load_variables_from_file
2023/03/30 21:35:29     Begin initialize_variables
2023/03/30 21:35:29     End initialize_variables
2023/03/30 21:35:29     ===> Step postinst. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:30     Begin save_wizard_variables
2023/03/30 21:35:30     End save_wizard_variables
2023/03/30 21:35:30     Begin syno_sync_var_folder
2023/03/30 21:35:30     Install files from var folder
2023/03/30 21:35:30     /bin/rsync -avh --ignore-existing --remove-source-files /volume1/@appstore/transmission/var/ /volume1/@appdata/transmission
2023/03/30 21:35:30     sending incremental file list
2023/03/30 21:35:30     ./
2023/03/30 21:35:30     sent 98 bytes  received 19 bytes  234.00 bytes/sec
2023/03/30 21:35:30     total size is 379  speedup is 3.24
2023/03/30 21:35:30     /bin/rsync -avh --remove-source-files /volume1/@appstore/transmission/var/ /volume1/@appdata/transmission
2023/03/30 21:35:31     sending incremental file list
2023/03/30 21:35:31     ./
2023/03/30 21:35:31     settings.json.new
2023/03/30 21:35:31     sent 533 bytes  received 46 bytes  1.16K bytes/sec
2023/03/30 21:35:31     total size is 379  speedup is 0.65
2023/03/30 21:35:31     End syno_sync_var_folder
2023/03/30 21:35:31     Begin service_postinst
2023/03/30 21:35:31     End service_postinst
2023/03/30 21:35:31     upgrade transmission 4.0.2-21 End postinst ret=[0]
2023/03/30 21:35:31     upgrade transmission 4.0.2-21 Begin postupgrade
2023/03/30 21:35:31     Begin load_variables_from_file
2023/03/30 21:35:31     End load_variables_from_file
2023/03/30 21:35:31     Begin initialize_variables
2023/03/30 21:35:31     End initialize_variables
2023/03/30 21:35:31     ===> Step postupgrade. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:31     Begin syno_sync_var_folder
2023/03/30 21:35:31     End syno_sync_var_folder
2023/03/30 21:35:32     upgrade transmission 4.0.2-21 End postupgrade ret=[0]
2023/03/30 21:35:36     upgrade transmission 4.0.2-21 Begin start-stop-status start
2023/03/30 21:35:38     upgrade transmission 4.0.2-21 End start-stop-status start ret=[0]
```

### Service Log

```log
Starting transmission command /volume1/@appstore/transmission/bin/transmission-daemon -g /volume1/@appdata/transmission -x /volume1/@appdata/transmission/transmission.pid -e /volume1/@appdata/transmission/transmission.log
```

### Other Logs

```log
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgtool.cpp:1741 chmod failed for /var/packages (Operation not permitted)
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgtool.cpp:1750 chmod failed for /usr/local/etc/rc.d (Operation not permitted)
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgfile.cpp:115 Failed to create directory, path=[/var/cache/synopkg/installed] err=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkginstalled_repository.cpp:66 Failed to mkdir for file, path=[/var/cache/synopkg/installed/dependency_graph] reason=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkginstalled_repository.cpp:120 Failed to put graph cache into file, path=[/var/cache/synopkg/installed/dependency_graph] reason=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgfile.cpp:115 Failed to create directory, path=[/run/synopkg/lock] err=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkglock_package_lock.cpp:44 Failed to create dir for lock, path=[/run/synopkg/lock/transmission.lock]
```

### PR DESCRIPTION
**Pull request by hgy59**
## Description

There is an issue with empty blocklist files for ARMv7 models.

- fix empty blocklist by patch
- fix file locking by patch for ARMv7 archs
- use TMP_DIR to avoid permission error logs for session files (this finally was only the flock problem with ARMv7, but IMHO it is anyway prefered to use the package tmp folder).
- update icon
- remove DSM 6 portions in service-setup.sh

Fixes #5685

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix

### CODE REVIEW

**Comment by hgy59** [comment]
@d4niel-P, @dwardor can you please test the armv7 package created by github build action?

_navigate to Checks - Build - Artifacts and download `Packages for armv7-7.1`_

**Comment by d4niel-P** [comment]
Sadly, it still doesn't work for me. I have no possibility to ssh to the NAS until Monday, so I'll check the logs and files next week.

BTW: I really appreciate the work you are putting into this. 👍

**Comment by dwardor** [comment]
blockfile is read and I have 81086 rules :-)
image

**Comment by hgy59** [comment]
> blockfile is read and I have 81086 rules :-)

@dwardor Thanks for the feedback.

There are still warnings in the log file, even when the blockfile is successfully created.
``` 
[2023-09-02 21:40:16.301] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Unable to read/write: Invalid argument (22) (blocklist.cc:505)
```

this I have locally fixed...

But there is another `Invalid argument` warning when creating the session file:
```
[2023-09-02 21:39:04.309] WRN session-id.cc:74 Couldn't create '/volume1/@apptemp/transmission/tr_session_id_1fdb5e2i88pxXb5MBuQnSxIkOTtPidEJr3HhgLynWMVLodcP': Invalid argument (22) (session-id.cc:74)
```

The session-id warning is not related to the blocklist warning. Will try to fix it too.


any feedback related to other warnings in transmission.log is welcome, particularly `Invalid argument (22)` ...

**Comment by dwardor** [comment]
> any feedback related to other warnings in transmission.log is welcome, particularly `Invalid argument (22)` ...

I also have the session-id "Invalid argument (22)"
`[2023-09-02 22:51:34.061] WRN session-id.cc:74 Couldn't create '/volume1/@apptemp/transmission/tr_session_id_I2Njnr5HBQcxWyvLh5zWk4aRQmsv3hg2dA7IfI6auweescxd': Invalid argument (22) (session-id.cc:74)`

File: spk/transmission/src/service-setup.sh
Comment (mreid-tt) [inline spk/transmission/src/service-setup.sh:1]: If we are getting rid of the logic for DSM < 7, then shouldn't we get rid of this too?

**Comment by mreid-tt** [comment]
https://github.com/SynoCommunity/spksrc/blob/9fc50151156ab7e47ab5333b987daf0fe0a54418/spk/transmission/src/service-setup.sh#L6-L9

If we are getting rid of the logic for DSM < 7, then shouldn't we get rid of this too?

File: spk/transmission/Makefile [hunk 1]
```diff
@@ -1,9 +1,12 @@
 SPK_NAME = transmission
 SPK_VERS = 4.0.4
-SPK_REV = 23
+SPK_REV = 24
 SPK_ICON = src/transmission.png
 
-DEPENDS = cross/$(SPK_NAME)
+DEPENDS = cross/transmission
+
+REQUIRED_MIN_DSM = 7.0
```
Comment (mreid-tt) [inline spk/transmission/Makefile:8]: This may have already been answered but curious as to why we need this duplicated here if it's already in the `cross` Makefile.

Comment (hgy59) [reply spk/transmission/Makefile:8]: 1. for clarity (I don't want to look into cross packages for such dependencies, when I have the focus on the spk files)
2. to avoid any download for unsupported archs/DSM version (I saw such downloads but can't remember the related packages, probably this is still an issue with BUILD_DEPENDS).

so we need the definition in cross and spk (as we might build in cross too).

**Comment by hgy59** [comment]
> > any feedback related to other warnings in transmission.log is welcome, particularly `Invalid argument (22)` ...
> 
> I also have the session-id "Invalid argument (22)" `[2023-09-02 22:51:34.061] WRN session-id.cc:74 Couldn't create '/volume1/@apptemp/transmission/tr_session_id_I2Njnr5HBQcxWyvLh5zWk4aRQmsv3hg2dA7IfI6auweescxd': Invalid argument (22) (session-id.cc:74)`

The invalid argument error comes from the call of `flock` when locking the session file. I didn't find a fix for this and don't know whether this is mandatory or not.
_I tried to call flock without the `LOCK_NB` (non blocking) flag set, but this results still in invalid argument, and I have not a clue, what argument is not valid._

File: spk/transmission/src/service-setup.sh [hunk 2]
```diff
@@ -1,16 +1,13 @@
+# use system python for DSM7
+PYTHON_BIN_PATHS=""
+
```
Comment (hgy59) [inline spk/transmission/src/service-setup.sh:3]: I would ommit this variable since it is a leftover of DSM 6 compatibility.

OR - it could be `PYTHON_BIN_PATH=$(which python3)` but this would be obsolete too...

OR - it could be used as precondition. If $(which python3) is empty, then the package should abort the installation.

OR - if python3 is not found in the path, take a python path from the user (in a wizard).


Another approach would be to write the python3 path into a config file at time of installation, and load this file in service-setup.sh to add the value of the variable to the PATH below. This enables an option for the user to manually configure (overwrite) the python path.
This is useful, when a python script depends on a newer python version than what Synology provides with DSM (i.e. you could configure the path of our python310 or python311 package).

Comment (mreid-tt) [reply spk/transmission/src/service-setup.sh:3]: I leave it to your discretion, no opinion here.

**Comment by d4niel-P** [comment]
>
> I'll check the logs and files next week.
> 

Nothing changed for me with 4.0.4-23. Still attempt to download the list ends with empty _blocklist_ file in _/volume1/@appdata/transmission/blocklists_ and logs show:

```
[2023-09-04 10:52:04.445] WRN blocklist.cc:242 Couldn't parse line: '83369' (blocklist.cc:242)
[2023-09-04 10:52:04.445] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Unable to read/write: Invalid argument (22) (blocklist.cc:505)
```

**Comment by mreid-tt** [comment]
> Nothing changed for me with 4.0.4-23. Still attempt to download the list ends with empty _blocklist_ file in _/volume1/@appdata/transmission/blocklists_ and logs show:
> 
> ```
> [2023-09-04 10:52:04.445] WRN blocklist.cc:242 Couldn't parse line: '83369' (blocklist.cc:242)
> [2023-09-04 10:52:04.445] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Unable to read/write: Invalid argument (22) (blocklist.cc:505)
> ```

@d4niel-P, v4.0.4-23 is the published version that does not include this fix; you need to test with the unpublished version (4.0.4-24). As indicated above, to install it you will need to manually download the spk file for your CPU arch from [here](https://github.com/SynoCommunity/spksrc/actions/runs/6066024950) and test with that.

**Comment by d4niel-P** [comment]
@mreid-tt Sorry, mb. I saw that 4.0.4-23 was updated on Saturday and I was sure for some reason that this version is with the hotfix already.

@hgy59 it works on 4.0.4-24:
obraz
 Thanks!

Logs still have the same WRNs though:
```
[2023-09-04 13:36:30.356] WRN blocklist.cc:242 Couldn't parse line: '83369' (blocklist.cc:242)
[2023-09-04 13:36:30.356] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Invalid argument (22) (blocklist.cc:505)
```

**Comment by hgy59** [comment]
> Logs still have the same WRNs though:
> 
> ```
> [2023-09-04 13:36:30.356] WRN blocklist.cc:242 Couldn't parse line: '83369' (blocklist.cc:242)
> [2023-09-04 13:36:30.356] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Invalid argument (22) (blocklist.cc:505)
> ```

The "invalid argument (22)" is fixed now.

The latest commit also fixes the lock of the session-id file that leads to warnings like:
```
[2023-09-02 22:51:34.061] WRN session-id.cc:74 Couldn't create '/volume1/@apptemp/transmission/tr_session_id_I2Njnr5HBQcxWyvLh5zWk4aRQmsv3hg2dA7IfI6auweescxd': Invalid argument (22) (session-id.cc:74)
```
The warning is missleading, the file could be created but not locked.
_BTW: locked files are listed with `lslocks`_

The additional warning:
```
[2023-09-04 13:36:30.356] WRN blocklist.cc:242 Couldn't parse line: '83369' (blocklist.cc:242)
```
This is related to the specified blocklist.
The text file is filled up with 0-byes after the last line
Those are not valid block list entries, hence it logs this warning.

File: spk/transmission/src/service-setup.sh (hunk 2 above)
Comment (hgy59) [reply spk/transmission/src/service-setup.sh]: @mreid-tt I removed the python path at all.

To execute python scripts with a non default python3, one can adjust the shebang in the script.

**Comment by hgy59** [comment]
@d4niel-P @dwardor a kind request for a final test. IMHO this is ready to merge.

**Comment by dwardor** [comment]
Can confirm that the "invalid argument (22) (session-id.cc:74)" is fixed now :-) !

**Review by mreid-tt — APPROVED** [review]

**Comment by mreid-tt** [comment]
LGTM 🚀
